import { type PersonalDetailsFormValues } from "@lib/validations/personal-details";

export const stepFields: Record<number, (keyof PersonalDetailsFormValues)[]> = {
  1: [
    "firstName",
    "lastName",
    "gender",
    "dob",
    "primaryMobile",
    "alternateMobile",
    "email",
    "presentAddressLine1",
    "presentState",
    "presentDistrict",
    "presentCity",
    "presentPincode",
    "permanentAddressLine1",
    "permanentState",
    "permanentDistrict",
    "permanentCity",
    "permanentPincode",
  ],
  2: [
    "bloodGroup",
    "aadhaarNo",
    "nameAsPerAadhaar",
    "panNo",
    "nameAsPerPan",
    "religion",
    "category",
    "maritalStatus",
    "anniversaryDate",
  ],
  3: ["family"],
  4: ["interviewedBefore", "workedBefore", "source"],
  5: ["education"],
  6: ["workExp"],
  7: [
    "serviceCommitment",
    "securityDeposit",
    "shiftTime",
    "expectedJoiningDate",
    "expectedSalary",
  ],
};

export const defaultPersonalDetailsValues2: PersonalDetailsFormValues = {
  firstName: "Mohammed",
  lastName: "Danish",
  gender: "Male",
  dob: "1998-05-15",
  primaryMobile: "",
  alternateMobile: "",
  email: "mohammed.danish@example.com",
  presentAddressLine1: "Arcgate IT Park",
  presentAddressLine2: "Sector 3, Hiranmagri",
  presentState: "Rajasthan",
  presentDistrict: "Udaipur",
  presentCity: "Udaipur",
  presentPincode: "313002",
  permanentAddressLine1: "",
  permanentAddressLine2: "",
  permanentState: "",
  permanentDistrict: "",
  permanentCity: "",
  permanentPincode: "",
  sameAddress: true,
  bloodGroup: "O+",
  aadhaarNo: "123456789012",
  nameAsPerAadhaar: "Mohammed Danish",
  panNo: "ABCDE1234F",
  nameAsPerPan: "Mohammed Danish",
  religion: "Islam",
  category: "General",
  maritalStatus: "Single",
  anniversaryDate: "",
  family: [
    {
      id: 1,
      relationLabel: "Father",
      relation: "Father",
      name: "Mohammed Sattar",
      occupation: "Business",
      dependent: "No",
    },
    {
      id: 2,
      relationLabel: "Mother",
      relation: "Mother",
      name: "Zareena Begum",
      occupation: "Homemaker",
      dependent: "No",
    },
  ],
  interviewedBefore: "No",
  workedBefore: "No",
  source: {
    campus: false,
    website: true,
    employee: false,
    friends: false,
    newspaper: false,
  },
  education: [
    {
      id: 1,
      type: "10th Std",
      school: "Delhi Public School",
      board: "CBSE",
      startYear: "2009",
      endYear: "2010",
      division: "1st",
      percentage: "85%",
      medium: "English",
      details: "All Subject",
    },
    {
      id: 2,
      type: "12th Std",
      school: "Delhi Public School",
      board: "CBSE",
      startYear: "2010",
      endYear: "2012",
      division: "1st",
      percentage: "82%",
      medium: "English",
      details: "Science",
    },
  ],
  workExp: [
    {
      id: 1,
      company: "Tech Solutions Pvt Ltd",
      employmentType: "FULL_TIME",
      designation: "Software Engineer",
      joinDate: "2018-06-01",
      relieveDate: "2022-06-01",
      reason: "Better opportunity",
      salary: "1000000",
    },
  ],
  serviceCommitment: "Yes",
  securityDeposit: "Yes",
  shiftTime: "Any",
  expectedJoiningDate: "2026-07-31",
  expectedSalary: "1200000",
  emergencyContactRelation: "",
  assignedEmergencyRelation: "",
};

export const defaultPersonalDetailsValues: PersonalDetailsFormValues = {
  firstName: "",
  lastName: "",
  gender: "Male",
  dob: "",
  primaryMobile: "",
  alternateMobile: "",
  email: "",
  presentAddressLine1: "",
  presentAddressLine2: "",
  presentState: "",
  presentDistrict: "",
  presentCity: "",
  presentPincode: "",
  permanentAddressLine1: "",
  permanentAddressLine2: "",
  permanentState: "",
  permanentDistrict: "",
  permanentCity: "",
  permanentPincode: "",
  sameAddress: false,
  bloodGroup: "",
  aadhaarNo: "",
  nameAsPerAadhaar: "",
  panNo: "",
  nameAsPerPan: "",
  religion: "",
  category: "",
  maritalStatus: "",
  anniversaryDate: "",
  family: [
    {
      id: 1,
      relationLabel: "Father",
      relation: "Father",
      name: "",
      occupation: "",
      dependent: "",
    },
    {
      id: 2,
      relationLabel: "Mother",
      relation: "Mother",
      name: "",
      occupation: "",
      dependent: "",
    },
  ],
  interviewedBefore: "",
  workedBefore: "",
  source: {
    campus: false,
    website: false,
    employee: false,
    friends: false,
    newspaper: false,
  },
  education: [
    {
      id: 1,
      type: "10th Std",
      school: "",
      board: "",
      startYear: "",
      endYear: "",
      division: "",
      percentage: "",
      medium: "",
      details: "",
    },
    {
      id: 2,
      type: "12th Std",
      school: "",
      board: "",
      startYear: "",
      endYear: "",
      division: "",
      percentage: "",
      medium: "",
      details: "",
    },
  ],
  workExp: [
    {
      id: 1,
      company: "",
      employmentType: "",
      designation: "",
      joinDate: "",
      relieveDate: "",
      reason: "",
      salary: "",
    },
  ],
  serviceCommitment: "",
  securityDeposit: "",
  shiftTime: "",
  expectedJoiningDate: "",
  expectedSalary: "",
  emergencyContactRelation: "",
  assignedEmergencyRelation: "",
};
