import { type PersonalDetailsFormValues } from "@lib/validations/personal-details";

export const stepFields: Record<number, (keyof PersonalDetailsFormValues)[]> = {
  1: [
    "firstName",
    "lastName",
    "gender",
    "dob",
    "primaryMobile",
    "alternateMobile",
    "email",
    "presentAddressLine1",
    "presentAddressLine2",
    "presentState",
    "presentDistrict",
    "presentCity",
    "presentPincode",
    "permanentAddressLine1",
    "permanentAddressLine2",
    "permanentState",
    "permanentDistrict",
    "permanentCity",
    "permanentPincode",
    "sameAddress",
  ],
  2: [
    "bloodGroup",
    "aadhaarNo",
    "nameAsPerAadhaar",
    "panNo",
    "nameAsPerPan",
    "religion",
    "category",
    "maritalStatus",
    "anniversaryDate",
    "emergencyContactRelation",
    "assignedEmergencyRelation",
  ],
  3: ["family"],
  4: ["interviewedBefore", "workedBefore", "source"],
  5: ["education"],
  6: ["workExp"],
  7: [
    "serviceCommitment",
    "securityDeposit",
    "shiftTime",
    "expectedJoiningDate",
    "expectedSalary",
  ],
};

export const defaultPersonalDetailsValues2: PersonalDetailsFormValues = {
  firstName: "",
  lastName: "",
  gender: "",
  dob: "",
  primaryMobile: "",
  alternateMobile: "",
  email: "",
  presentAddressLine1: "",
  presentAddressLine2: "",
  presentState: "",
  presentDistrict: "",
  presentCity: "",
  presentPincode: "",
  permanentAddressLine1: "",
  permanentAddressLine2: "",
  permanentState: "",
  permanentDistrict: "",
  permanentCity: "",
  permanentPincode: "",
  sameAddress: false,
  bloodGroup: "",
  aadhaarNo: "",
  nameAsPerAadhaar: "",
  panNo: "",
  nameAsPerPan: "",
  religion: "",
  category: "",
  maritalStatus: "",
  anniversaryDate: "",
  family: [
    {
      id: 1,
      relationLabel: "Father",
      relation: "FATHER",
      name: "",
      occupation: "",
      dependent: "No",
    },
    {
      id: 2,
      relationLabel: "Mother",
      relation: "MOTHER",
      name: "",
      occupation: "",
      dependent: "No",
    },
  ],
  interviewedBefore: false,
  workedBefore: false,
  source: {
    campus: false,
    website: false,
    employee: false,
    friends: false,
    newspaper: false,
    others: false,
    otherDetails: "",
  },
  education: [
    {
      id: 1,
      type: "10th Std",
      school: "",
      board: "",
      startYear: "",
      endYear: "",
      division: "",
      percentage: "",
      medium: "",
      details: "",
    },
    {
      id: 2,
      type: "12th Std",
      school: "",
      board: "",
      startYear: "",
      endYear: "",
      division: "",
      percentage: "",
      medium: "",
      details: "",
    },
  ],
  workExp: [
    {
      id: 1,
      company: "",
      employmentType: "",
      designation: "",
      joinDate: "",
      relieveDate: "",
      reason: "",
      salary: "",
    },
  ],
  serviceCommitment: "",
  securityDeposit: "",
  shiftTime: "",
  expectedJoiningDate: "",
  expectedSalary: "",
  emergencyContactRelation: "",
  assignedEmergencyRelation: "",
};

export const defaultPersonalDetailsValues: PersonalDetailsFormValues = {
  firstName: "Rahul",
  lastName: "Sharma",
  gender: "Male",
  dob: "1998-05-15",
  primaryMobile: "9876543212",
  alternateMobile: "9876543211",
  email: "rahul.sharma@example.com",
  presentAddressLine1: "123, Panchsheel Nagar",
  presentAddressLine2: "Near Ana Sagar Lake",
  presentState: "Rajasthan",
  presentDistrict: "Ajmer",
  presentCity: "Ajmer",
  presentPincode: "305001",
  permanentAddressLine1: "123, Panchsheel Nagar",
  permanentAddressLine2: "Near Ana Sagar Lake",
  permanentState: "Rajasthan",
  permanentDistrict: "Ajmer",
  permanentCity: "Ajmer",
  permanentPincode: "305001",
  sameAddress: true,
  bloodGroup: "O+",
  aadhaarNo: "123456789012",
  nameAsPerAadhaar: "Rahul Sharma",
  panNo: "ABCDE1234F",
  nameAsPerPan: "Rahul Sharma",
  religion: "Hinduism",
  category: "General",
  maritalStatus: "Married",
  anniversaryDate: "2021-11-25",
  family: [
    {
      id: 1,
      relationLabel: "Father",
      relation: "FATHER",
      name: "Ramesh Sharma",
      occupation: "Business",
      dependent: "No",
    },
    {
      id: 2,
      relationLabel: "Mother",
      relation: "MOTHER",
      name: "Sunita Sharma",
      occupation: "Homemaker",
      dependent: "Yes",
    },
    {
      id: 3,
      relationLabel: "Wife",
      relation: "WIFE",
      name: "Pooja Sharma",
      occupation: "Teacher",
      dependent: "Yes",
    },
    {
      id: 4,
      relationLabel: "Son",
      relation: "SON",
      name: "Aarav Sharma",
      occupation: "Student",
      dependent: "Yes",
    },
    {
      id: 5,
      relationLabel: "Daughter",
      relation: "DAUGHTER",
      name: "Ananya Sharma",
      occupation: "Student",
      dependent: "Yes",
    },
    {
      id: 6,
      relationLabel: "Brother",
      relation: "BROTHER",
      name: "Vikas Sharma",
      occupation: "Engineer",
      dependent: "No",
    },
    {
      id: 7,
      relationLabel: "Sister",
      relation: "SISTER",
      name: "Neha Sharma",
      occupation: "Doctor",
      dependent: "No",
    },
  ],
  interviewedBefore: false,
  workedBefore: false,
  source: {
    campus: false,
    website: true,
    employee: false,
    friends: true,
    newspaper: false,
    others: true,
    otherDetails: "Job Fair 2026",
  },
  education: [
    {
      id: 1,
      type: "10th Std",
      school: "St. Anselm's Sr Sec School",
      board: "CBSE",
      startYear: "2010",
      endYear: "2011",
      division: "First",
      percentage: "88",
      medium: "English",
      details: "Science & Math",
    },
    {
      id: 2,
      type: "12th Std",
      school: "Government Sr Sec School",
      board: "RBSE",
      startYear: "2012",
      endYear: "2013",
      division: "First",
      percentage: "86",
      medium: "English",
      details: "Physics, Chemistry, Math",
    },
    {
      id: 3,
      type: "Diploma",
      school: "Government Polytechnic College Ajmer",
      board: "BTER",
      startYear: "2013",
      endYear: "2015",
      division: "First",
      percentage: "82",
      medium: "English",
      details: "Diploma Computer Engineering",
    },
    {
      id: 4,
      type: "Graduation",
      school: "Engineering College Ajmer",
      board: "RTU Kota",
      startYear: "2015",
      endYear: "2018",
      division: "First (A+)",
      percentage: "9.2",
      medium: "English",
      details: "B.Tech Computer Science",
    },
    {
      id: 5,
      type: "Post Graduation",
      school: "MNIT Jaipur",
      board: "MNIT",
      startYear: "2018",
      endYear: "2020",
      division: "First (O)",
      percentage: "9.6",
      medium: "English",
      details: "M.Tech Data Science",
    },
    {
      id: 6,
      type: "Doctorate (PhD)",
      school: "Central University of Rajasthan",
      board: "CURAJ",
      startYear: "2020",
      endYear: "2023",
      division: "First (O)",
      percentage: "9.8",
      medium: "English",
      details: "Ph.D Artificial Intelligence",
    },
  ],
  workExp: [
    {
      id: 1,
      company: "TCS (Tata Consultancy Services)",
      employmentType: "Full Time",
      designation: "Systems Engineer",
      joinDate: "2020-07-01",
      relieveDate: "2021-06-30",
      reason: "Better Opportunity",
      salary: "35000",
    },
    {
      id: 2,
      company: "Infosys Limited",
      employmentType: "Full Time",
      designation: "Senior Software Engineer",
      joinDate: "2021-07-15",
      relieveDate: "2022-08-31",
      reason: "Relocation",
      salary: "50000",
    },
    {
      id: 3,
      company: "Wipro Technologies",
      employmentType: "Full Time",
      designation: "Lead Developer",
      joinDate: "2022-09-01",
      relieveDate: "2023-11-30",
      reason: "Role Enhancement",
      salary: "70000",
    },
    {
      id: 4,
      company: "Tech Mahindra",
      employmentType: "Full Time",
      designation: "Associate Architect",
      joinDate: "2023-12-01",
      relieveDate: "2025-01-31",
      reason: "Higher Responsibilities",
      salary: "90000",
    },
    {
      id: 5,
      company: "Arcgate Solutions",
      employmentType: "Full Time",
      designation: "Principal AI Engineer",
      joinDate: "2025-02-01",
      relieveDate: "2026-07-31",
      reason: "Career Growth",
      salary: "120000",
    },
  ],
  serviceCommitment: "Yes",
  securityDeposit: "Yes",
  shiftTime: "Day Shift",
  expectedJoiningDate: "2026-08-15",
  expectedSalary: "150000",
  emergencyContactRelation: "FATHER",
  assignedEmergencyRelation: "FATHER",
};
