import { type PersonalDetailsFormValues } from "@lib/validations/personal-details";

export const stepFields: Record<number, (keyof PersonalDetailsFormValues)[]> = {
  1: [
    "firstName",
    "lastName",
    "gender",
    "dob",
    "primaryMobile",
    "alternateMobile",
    "email",
    "presentAddressLine1",
    "presentState",
    "presentDistrict",
    "presentCity",
    "presentPincode",
    "permanentAddressLine1",
    "permanentState",
    "permanentDistrict",
    "permanentCity",
    "permanentPincode",
  ],
  2: [
    "bloodGroup",
    "aadhaarNo",
    "nameAsPerAadhaar",
    "panNo",
    "nameAsPerPan",
    "religion",
    "category",
    "maritalStatus",
    "anniversaryDate",
  ],
  3: ["family"],
  4: ["interviewedBefore", "workedBefore", "source"],
  5: ["education"],
  6: ["workExp"],
  7: [
    "serviceCommitment",
    "securityDeposit",
    "shiftTime",
    "expectedJoiningDate",
    "expectedSalary",
  ],
};

export const defaultPersonalDetailsValues2: PersonalDetailsFormValues = {
  firstName: "Mohammed",
  lastName: "Mustafa",
  gender: "Male",
  dob: "1998-05-15",
  primaryMobile: "",
  alternateMobile: "",
  email: "mm@example.com",
  presentAddressLine1: "Arcgate IT Park",
  presentAddressLine2: "Sector 3, Hiranmagri",
  presentState: "Rajasthan",
  presentDistrict: "Udaipur",
  presentCity: "Udaipur",
  presentPincode: "313002",
  permanentAddressLine1: "",
  permanentAddressLine2: "",
  permanentState: "",
  permanentDistrict: "",
  permanentCity: "",
  permanentPincode: "",
  sameAddress: true,
  bloodGroup: "O+",
  aadhaarNo: "123456789012",
  nameAsPerAadhaar: "Mohammed Danish",
  panNo: "ABCDE1234F",
  nameAsPerPan: "Mohammed Danish",
  religion: "Islam",
  category: "General",
  maritalStatus: "Married",
  anniversaryDate: "2022-11-20",
  family: [
    {
      id: 1,
      relationLabel: "Father",
      relation: "FATHER",
      name: "Mohammed Sattar",
      occupation: "Business",
      dependent: "No",
      contactNo: "9876543210",
    },
    {
      id: 2,
      relationLabel: "Mother",
      relation: "MOTHER",
      name: "Zareena Begum",
      occupation: "Homemaker",
      dependent: "No",
      contactNo: "",
    },
    {
      id: 3,
      relationLabel: "Wife",
      relation: "WIFE",
      name: "Sana Khan",
      occupation: "Software Engineer",
      dependent: "Yes",
      contactNo: "",
    },
    {
      id: 4,
      relationLabel: "Son",
      relation: "SON",
      name: "Zayd Danish",
      occupation: "Student",
      dependent: "Yes",
      contactNo: "",
    },
    {
      id: 5,
      relationLabel: "Daughter",
      relation: "DAUGHTER",
      name: "Zara",
      occupation: "Student",
      dependent: "Yes",
      contactNo: "",
    },
    {
      id: 6,
      relationLabel: "Brother",
      relation: "BROTHER",
      name: "Aamir",
      occupation: "Business",
      dependent: "No",
      contactNo: "",
    },
    {
      id: 7,
      relationLabel: "Sister",
      relation: "SISTER",
      name: "Yasmin",
      occupation: "Student",
      dependent: "No",
      contactNo: "",
    },
  ],
  interviewedBefore: "No",
  workedBefore: "No",
  source: {
    campus: false,
    website: true,
    employee: false,
    friends: false,
    newspaper: false,
  },
  education: [
    {
      id: 1,
      type: "10th Std",
      school: "Delhi Public School",
      board: "CBSE",
      startYear: "2004",
      endYear: "2006",
      division: "1st",
      percentage: "85%",
      medium: "English",
      details: "All Subjects",
    },
    {
      id: 2,
      type: "12th Std",
      school: "Delhi Public School",
      board: "CBSE",
      startYear: "2006",
      endYear: "2008",
      division: "1st",
      percentage: "82%",
      medium: "English",
      details: "Science",
    },
    {
      id: 3,
      type: "Diploma",
      school: "Government Polytechnic",
      board: "BTER",
      startYear: "2008",
      endYear: "2010",
      division: "1st",
      percentage: "90%",
      medium: "English",
      details: "Information Technology",
    },
    {
      id: 4,
      type: "Bachelor's Degree",
      school: "Rajasthan Technical University",
      board: "RTU",
      startYear: "2010",
      endYear: "2014",
      division: "1st",
      percentage: "78%",
      medium: "English",
      details: "Computer Science",
    },
    {
      id: 5,
      type: "Master's Degree",
      school: "IIT Bombay",
      board: "IIT",
      startYear: "2014",
      endYear: "2016",
      division: "1st",
      percentage: "85%",
      medium: "English",
      details: "Computer Science and Engineering",
    },
    {
      id: 6,
      type: "Ph.D. / Doctorate",
      school: "IISc Bangalore",
      board: "IISc",
      startYear: "2016",
      endYear: "2020",
      division: "1st",
      percentage: "92%",
      medium: "English",
      details: "Artificial Intelligence",
    },
  ],
  workExp: [
    {
      id: 1,
      company: "Tech Solutions Pvt Ltd",
      employmentType: "FULL_TIME",
      designation: "Software Engineer",
      joinDate: "2018-06-01",
      relieveDate: "2020-05-31",
      reason: "Better opportunity",
      salary: "1000000",
    },
    {
      id: 2,
      company: "Innova Web Tech",
      employmentType: "FULL_TIME",
      designation: "Senior Developer",
      joinDate: "2020-06-01",
      relieveDate: "2021-03-31",
      reason: "Relocation",
      salary: "1200000",
    },
    {
      id: 3,
      company: "Digital Core Inc",
      employmentType: "FULL_TIME",
      designation: "Tech Lead",
      joinDate: "2021-04-01",
      relieveDate: "2021-12-31",
      reason: "Company restructure",
      salary: "1500000",
    },
    {
      id: 4,
      company: "Global Systems Ltd",
      employmentType: "CONTRACT",
      designation: "Contract consultant",
      joinDate: "2022-01-01",
      relieveDate: "2022-06-30",
      reason: "End of contract",
      salary: "1800000",
    },
    {
      id: 5,
      company: "Cloud Services Corp",
      employmentType: "FULL_TIME",
      designation: "Solutions Architect",
      joinDate: "2022-07-01",
      relieveDate: "2023-02-28",
      reason: "Career growth",
      salary: "2000000",
    },
    {
      id: 6,
      company: "AI Labs India",
      employmentType: "FULL_TIME",
      designation: "Lead AI Engineer",
      joinDate: "2023-03-01",
      relieveDate: "2023-11-30",
      reason: "Personal reasons",
      salary: "2400000",
    },
    {
      id: 7,
      company: "NextGen Software",
      employmentType: "PART_TIME",
      designation: "Part-time Instructor",
      joinDate: "2023-12-01",
      relieveDate: "2024-04-30",
      reason: "Work life balance",
      salary: "600000",
    },
    {
      id: 8,
      company: "Apex Consulting",
      employmentType: "FULL_TIME",
      designation: "Manager IT",
      joinDate: "2024-05-01",
      relieveDate: "2024-12-31",
      reason: "Acquisition",
      salary: "2800000",
    },
    {
      id: 9,
      company: "Prime Tech Solutions",
      employmentType: "FULL_TIME",
      designation: "Associate Director",
      joinDate: "2025-01-01",
      relieveDate: "2025-09-30",
      reason: "Better compensation",
      salary: "3200000",
    },
    {
      id: 10,
      company: "Talent Flow Inc",
      employmentType: "FULL_TIME",
      designation: "Director of Engineering",
      joinDate: "2025-10-01",
      relieveDate: "2026-06-30",
      reason: "Active search",
      salary: "3600000",
    },
  ],
  serviceCommitment: "Yes",
  securityDeposit: "Yes",
  shiftTime: "Any",
  expectedJoiningDate: "2026-07-31",
  expectedSalary: "1200000",
  emergencyContactRelation: "FATHER",
  assignedEmergencyRelation: "FATHER",
};

export const defaultPersonalDetailsValues: PersonalDetailsFormValues = {
  firstName: "",
  lastName: "",
  gender: "",
  dob: "",
  primaryMobile: "",
  alternateMobile: "",
  email: "",
  presentAddressLine1: "",
  presentAddressLine2: "",
  presentState: "",
  presentDistrict: "",
  presentCity: "",
  presentPincode: "",
  permanentAddressLine1: "",
  permanentAddressLine2: "",
  permanentState: "",
  permanentDistrict: "",
  permanentCity: "",
  permanentPincode: "",
  sameAddress: false,
  bloodGroup: "",
  aadhaarNo: "",
  nameAsPerAadhaar: "",
  panNo: "",
  nameAsPerPan: "",
  religion: "",
  category: "",
  maritalStatus: "",
  anniversaryDate: "",
  family: [
    {
      id: 1,
      relationLabel: "Father",
      relation: "FATHER",
      name: "",
      occupation: "",
      dependent: "",
    },
    {
      id: 2,
      relationLabel: "Mother",
      relation: "MOTHER",
      name: "",
      occupation: "",
      dependent: "",
    },
  ],
  interviewedBefore: "",
  workedBefore: "",
  source: {
    campus: false,
    website: false,
    employee: false,
    friends: false,
    newspaper: false,
  },
  education: [
    {
      id: 1,
      type: "10th Std",
      school: "",
      board: "",
      startYear: "",
      endYear: "",
      division: "",
      percentage: "",
      medium: "",
      details: "",
    },
    {
      id: 2,
      type: "12th Std",
      school: "",
      board: "",
      startYear: "",
      endYear: "",
      division: "",
      percentage: "",
      medium: "",
      details: "",
    },
  ],
  workExp: [
    {
      id: 1,
      company: "",
      employmentType: "",
      designation: "",
      joinDate: "",
      relieveDate: "",
      reason: "",
      salary: "",
    },
  ],
  serviceCommitment: "",
  securityDeposit: "",
  shiftTime: "",
  expectedJoiningDate: "",
  expectedSalary: "",
  emergencyContactRelation: "",
  assignedEmergencyRelation: "",
};
