from enum import Enum


class QuestionType(str, Enum):
    MULTIPLE_CHOICE = "MULTIPLE_CHOICE"
    IMAGE_MULTIPLE_CHOICE = "IMAGE_MULTIPLE_CHOICE"
    SUBJECTIVE = "SUBJECTIVE"
    IMAGE_SUBJECTIVE = "IMAGE_SUBJECTIVE"
    PASSAGE_CONTENT = "PASSAGE_CONTENT"
    TYPING_TEST = "TYPING_TEST"
    LEAD_GENERATION = "LEAD_GENERATION"
    CONTACT_DETAILS = "CONTACT_DETAILS"
