import { type PersonalDetailsFormValues } from "@lib/validations/personal-details";

export const stepFields: Record<number, (keyof PersonalDetailsFormValues)[]> = {
  1: [
    "firstName",
    "lastName",
    "gender",
    "dob",
    "primaryMobile",
    "alternateMobile",
    "email",
    "presentAddressLine1",
    "presentState",
    "presentDistrict",
    "presentCity",
    "presentPincode",
    "permanentAddressLine1",
    "permanentState",
    "permanentDistrict",
    "permanentCity",
    "permanentPincode",
  ],
  2: ["family"],
  3: ["interviewedBefore", "workedBefore", "source"],
  4: ["education"],
  5: ["workExp"],
  6: [
    "serviceCommitment",
    "securityDeposit",
    "shiftTime",
    "expectedJoiningDate",
    "expectedSalary",
  ],
};

export const defaultPersonalDetailsValues: PersonalDetailsFormValues = {
  firstName: "John",
  lastName: "Doe",
  gender: "Male",
  dob: "1995-05-15",
  primaryMobile: "9876543210",
  alternateMobile: "",
  email: "john.doe@example.com",
  presentAddressLine1: "123 Random Street, Apt 4B",
  presentAddressLine2: "",
  presentState: "Maharashtra",
  presentDistrict: "Mumbai",
  presentCity: "Mumbai",
  presentPincode: "400001",
  permanentAddressLine1: "",
  permanentAddressLine2: "",
  permanentState: "",
  permanentDistrict: "",
  permanentCity: "",
  permanentPincode: "",
  sameAddress: true,
  family: [
    {
      id: 1,
      relationLabel: "Father",
      relation: "Father",
      name: "Michael Doe",
      occupation: "Engineer",
      dependent: "No",
    },
    {
      id: 2,
      relationLabel: "Mother",
      relation: "Mother",
      name: "Sarah Doe",
      occupation: "Teacher",
      dependent: "No",
    },
    {
      id: 3,
      relationLabel: "Spouse",
      relation: "Spouse",
      name: "",
      occupation: "",
      dependent: "",
    },
    {
      id: 4,
      relationLabel: "Brother/Sister",
      relation: "",
      name: "",
      occupation: "",
      dependent: "",
    },
    {
      id: 5,
      relationLabel: "Brother/Sister",
      relation: "",
      name: "",
      occupation: "",
      dependent: "",
    },
    {
      id: 6,
      relationLabel: "Brother/Sister",
      relation: "",
      name: "",
      occupation: "",
      dependent: "",
    },
  ],
  interviewedBefore: "No",
  workedBefore: "No",
  source: {
    campus: false,
    website: true,
    employee: false,
    friends: false,
    newspaper: false,
  },
  education: [
    {
      id: 1,
      type: "10th Std",
      school: "Delhi Public School",
      board: "CBSE",
      year: "2010",
      division: "1st",
      percentage: "85%",
      medium: "English",
    },
    {
      id: 2,
      type: "12th Std",
      school: "Delhi Public School",
      board: "CBSE",
      year: "2012",
      division: "1st",
      percentage: "82%",
      medium: "English",
    },
    {
      id: 3,
      type: "Diploma",
      school: "",
      board: "",
      year: "",
      division: "",
      percentage: "",
      medium: "",
    },
    {
      id: 4,
      type: "Graduation",
      school: "IIT Bombay",
      board: "University of Mumbai",
      year: "2016",
      division: "1st",
      percentage: "90%",
      medium: "English",
    },
    {
      id: 5,
      type: "Post Graduation",
      school: "",
      board: "",
      year: "",
      division: "",
      percentage: "",
      medium: "",
    },
    {
      id: 6,
      type: "Additional Qualification",
      school: "",
      board: "",
      year: "",
      division: "",
      percentage: "",
      medium: "",
    },
  ],
  workExp: [
    {
      id: 1,
      company: "Tech Solutions Pvt Ltd",
      designation: "Software Engineer",
      joinDate: "2018-06-01",
      relieveDate: "2022-06-01",
      reason: "Better opportunity",
      salary: "1000000",
    },
    {
      id: 2,
      company: "",
      designation: "",
      joinDate: "",
      relieveDate: "",
      reason: "",
      salary: "",
    },
    {
      id: 3,
      company: "",
      designation: "",
      joinDate: "",
      relieveDate: "",
      reason: "",
      salary: "",
    },
    {
      id: 4,
      company: "",
      designation: "",
      joinDate: "",
      relieveDate: "",
      reason: "",
      salary: "",
    },
  ],
  serviceCommitment: "Yes",
  securityDeposit: "Yes",
  shiftTime: "Any",
  expectedJoiningDate: "2024-06-01",
  expectedSalary: "1200000",
};

export const defaultPersonalDetailsValues2: PersonalDetailsFormValues = {
  firstName: "",
  lastName: "",
  gender: "Male",
  dob: "",
  primaryMobile: "",
  alternateMobile: "",
  email: "",
  presentAddressLine1: "",
  presentAddressLine2: "",
  presentState: "",
  presentDistrict: "",
  presentCity: "",
  presentPincode: "",
  permanentAddressLine1: "",
  permanentAddressLine2: "",
  permanentState: "",
  permanentDistrict: "",
  permanentCity: "",
  permanentPincode: "",
  sameAddress: false,
  family: [
    {
      id: 1,
      relationLabel: "Father",
      relation: "Father",
      name: "",
      occupation: "",
      dependent: "",
    },
    {
      id: 2,
      relationLabel: "Mother",
      relation: "Mother",
      name: "",
      occupation: "",
      dependent: "",
    },
    {
      id: 3,
      relationLabel: "Spouse",
      relation: "Spouse",
      name: "",
      occupation: "",
      dependent: "",
    },
    {
      id: 4,
      relationLabel: "Brother/Sister",
      relation: "",
      name: "",
      occupation: "",
      dependent: "",
    },
    {
      id: 5,
      relationLabel: "Brother/Sister",
      relation: "",
      name: "",
      occupation: "",
      dependent: "",
    },
    {
      id: 6,
      relationLabel: "Brother/Sister",
      relation: "",
      name: "",
      occupation: "",
      dependent: "",
    },
  ],
  interviewedBefore: "",
  workedBefore: "",
  source: {
    campus: false,
    website: false,
    employee: false,
    friends: false,
    newspaper: false,
  },
  education: [
    {
      id: 1,
      type: "10th Std",
      school: "",
      board: "",
      year: "",
      division: "",
      percentage: "",
      medium: "",
    },
    {
      id: 2,
      type: "12th Std",
      school: "",
      board: "",
      year: "",
      division: "",
      percentage: "",
      medium: "",
    },
    {
      id: 3,
      type: "Diploma",
      school: "",
      board: "",
      year: "",
      division: "",
      percentage: "",
      medium: "",
    },
    {
      id: 4,
      type: "Graduation",
      school: "",
      board: "",
      year: "",
      division: "",
      percentage: "",
      medium: "",
    },
    {
      id: 5,
      type: "Post Graduation",
      school: "",
      board: "",
      year: "",
      division: "",
      percentage: "",
      medium: "",
    },
    {
      id: 6,
      type: "Additional Qualification",
      school: "",
      board: "",
      year: "",
      division: "",
      percentage: "",
      medium: "",
    },
  ],
  workExp: [
    {
      id: 1,
      company: "",
      designation: "",
      joinDate: "",
      relieveDate: "",
      reason: "",
      salary: "",
    },
    {
      id: 2,
      company: "",
      designation: "",
      joinDate: "",
      relieveDate: "",
      reason: "",
      salary: "",
    },
    {
      id: 3,
      company: "",
      designation: "",
      joinDate: "",
      relieveDate: "",
      reason: "",
      salary: "",
    },
    {
      id: 4,
      company: "",
      designation: "",
      joinDate: "",
      relieveDate: "",
      reason: "",
      salary: "",
    },
  ],
  serviceCommitment: "",
  securityDeposit: "",
  shiftTime: "",
  expectedJoiningDate: "",
  expectedSalary: "",
};
