"""add_status_time_marks_to_papers

Revision ID: 1043a67c6410
Revises: e4adefe9fcb0
Create Date: 2026-03-13 11:55:43.146088
Created By: md-danish-ai

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1043a67c6410"
down_revision: Union[str, Sequence[str], None] = "e4adefe9fcb0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "papers", sa.Column("total_time", sa.String(length=50), nullable=True)
    )
    op.add_column("papers", sa.Column("total_marks", sa.Integer(), nullable=True))
    op.add_column(
        "papers",
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("papers", "is_active")
    op.drop_column("papers", "total_marks")
    op.drop_column("papers", "total_time")
    # ### end Alembic commands ###
