
"""drop_paper_audit_logs

Revision ID: 10c5585e78a2
Revises: f9c3d01ae46e
Create Date: 2026-04-15 16:35:10.389513
Created By: md-danish-ai

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '10c5585e78a2'
down_revision: Union[str, Sequence[str], None] = 'f9c3d01ae46e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Using IF EXISTS to prevent failure on fresh database states
    op.execute("DROP INDEX IF EXISTS ix_paper_audit_logs_id")
    op.execute("DROP TABLE IF EXISTS paper_audit_logs")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper_audit_logs',
                    sa.Column('id', sa.INTEGER(),
                              autoincrement=True, nullable=False),
                    sa.Column('paper_id', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('updated_by', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('change_type', sa.VARCHAR(length=50),
                              autoincrement=False, nullable=False),
                    sa.Column('old_value', postgresql.JSONB(
                        astext_type=sa.Text()), autoincrement=False, nullable=True),
                    sa.Column('new_value', postgresql.JSONB(
                        astext_type=sa.Text()), autoincrement=False, nullable=True),
                    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text(
                        'CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], name=op.f(
                        'paper_audit_logs_paper_id_fkey'), ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f(
                        'paper_audit_logs_updated_by_fkey')),
                    sa.PrimaryKeyConstraint(
                        'id', name=op.f('paper_audit_logs_pkey'))
                    )
    op.create_index(op.f('ix_paper_audit_logs_id'),
                    'paper_audit_logs', ['id'], unique=False)
    # ### end Alembic commands ###
