
"""add_grade_snapshot_and_audit_log

Revision ID: 24413fcd3336
Revises: 55ba927acb0f
Create Date: 2026-04-13 10:42:38.847005
Created By: md-danish-ai

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '24413fcd3336'
down_revision: Union[str, Sequence[str], None] = '55ba927acb0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper_grade_setting_logs',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('paper_id', sa.Integer(), nullable=False),
                    sa.Column('updated_by', sa.Integer(), nullable=False),
                    sa.Column('old_grade_settings', postgresql.JSONB(
                        astext_type=sa.Text()), nullable=True),
                    sa.Column('new_grade_settings', postgresql.JSONB(
                        astext_type=sa.Text()), nullable=True),
                    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text(
                        'CURRENT_TIMESTAMP'), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['paper_id'], ['papers.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_paper_grade_setting_logs_id'),
                    'paper_grade_setting_logs', ['id'], unique=False)
    op.add_column('interview_attempts', sa.Column(
        'grade_settings_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    
    # Backfill missing snapshot data from current papers
    op.execute(
        """
        UPDATE interview_attempts
        SET grade_settings_snapshot = p.grade_settings
        FROM papers p
        WHERE interview_attempts.paper_id = p.id
        AND interview_attempts.grade_settings_snapshot IS NULL
        AND interview_attempts.status IN ('submitted', 'auto_submitted')
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_attempts', 'grade_settings_snapshot')
    op.drop_index(op.f('ix_paper_grade_setting_logs_id'),
                  table_name='paper_grade_setting_logs')
    op.drop_table('paper_grade_setting_logs')
    # ### end Alembic commands ###
