
"""add process_status to users

Revision ID: 28004a445359
Revises: c8d7f6e5d4c3
Create Date: 2026-04-23 14:03:52.722229
Created By: unknown

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28004a445359'
down_revision: Union[str, Sequence[str], None] = 'c8d7f6e5d4c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_questions_subject_level_type_marks', 'questions', ['subject_type', 'exam_level', 'question_type', 'marks', 'is_active'], unique=False)
    op.add_column('users', sa.Column('process_status', sa.String(length=50), server_default=sa.text("'pending'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'process_status')
    op.drop_index('ix_questions_subject_level_type_marks', table_name='questions')
    # ### end Alembic commands ###
