
"""add manual marks

Revision ID: 3adee8ecf3e9
Revises: 5b7f0f5e0aa1
Create Date: 2026-04-06 11:49:43.675612
Created By: md-danish-ai

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3adee8ecf3e9'
down_revision: Union[str, Sequence[str], None] = '5b7f0f5e0aa1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_attempt_responses', sa.Column(
        'manual_marks', sa.Numeric(precision=10, scale=2), nullable=True))
    op.alter_column('paper_assignments', 'is_attempted',
                    existing_type=sa.BOOLEAN(),
                    server_default=None,
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('paper_assignments', 'is_attempted',
                    existing_type=sa.BOOLEAN(),
                    server_default=sa.text('false'),
                    existing_nullable=False)
    op.drop_column('interview_attempt_responses', 'manual_marks')
    # ### end Alembic commands ###
