
"""add unique constraint for code column in classification table

Revision ID: 6ccb1459372e
Revises: f663a63eefc8
Create Date: 2026-02-27 17:22:12.222486
Created By: rahul-arcgate

"""
from typing import Sequence, Union

from alembic import op



# revision identifiers, used by Alembic.
revision: str = '6ccb1459372e'
down_revision: Union[str, Sequence[str], None] = 'f663a63eefc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'classifications', ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'classifications', type_='unique')
    # ### end Alembic commands ###
