"""add_user_id_to_notifications

Revision ID: 7a5eaaff678c
Revises: b8b26792b253
Create Date: 2026-05-07 15:43:52.970885
Created By: md-danish-ai

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7a5eaaff678c"
down_revision: Union[str, Sequence[str], None] = "b8b26792b253"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "admin_notifications", sa.Column("user_id", sa.Integer(), nullable=True)
    )
    op.create_index(
        op.f("ix_admin_notifications_user_id"),
        "admin_notifications",
        ["user_id"],
        unique=False,
    )
    op.create_foreign_key(None, "admin_notifications", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "admin_notifications", type_="foreignkey")
    op.drop_index(
        op.f("ix_admin_notifications_user_id"), table_name="admin_notifications"
    )
    op.drop_column("admin_notifications", "user_id")
    # ### end Alembic commands ###
