"""Add duplicate tracking tables

Revision ID: 8255fabdad40
Revises: bf8fe6b7d98a
Create Date: 2026-03-10 05:37:08.405349
Created By: md-danish-ai

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8255fabdad40"
down_revision: Union[str, Sequence[str], None] = "bf8fe6b7d98a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "duplicate_user_matches",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("new_user_id", sa.Integer(), nullable=False),
        sa.Column("matched_user_id", sa.Integer(), nullable=False),
        sa.Column("primary_score", sa.Float(), nullable=False),
        sa.Column("final_score", sa.Float(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("is_reviewed", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["matched_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["new_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_duplicate_user_matches_id"),
        "duplicate_user_matches",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_duplicate_user_matches_matched_user_id"),
        "duplicate_user_matches",
        ["matched_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_duplicate_user_matches_new_user_id"),
        "duplicate_user_matches",
        ["new_user_id"],
        unique=False,
    )
    op.create_table(
        "admin_notifications",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("type", sa.String(length=100), nullable=False),
        sa.Column("reference_id", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["reference_id"],
            ["duplicate_user_matches.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_admin_notifications_id"), "admin_notifications", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_admin_notifications_id"),
                  table_name="admin_notifications")
    op.drop_table("admin_notifications")
    op.drop_index(
        op.f("ix_duplicate_user_matches_new_user_id"),
        table_name="duplicate_user_matches",
    )
    op.drop_index(
        op.f("ix_duplicate_user_matches_matched_user_id"),
        table_name="duplicate_user_matches",
    )
    op.drop_index(
        op.f("ix_duplicate_user_matches_id"), table_name="duplicate_user_matches"
    )
    op.drop_table("duplicate_user_matches")
    # ### end Alembic commands ###
