
"""update the questions table schema and delete options table

Revision ID: a16a06a78ad1
Revises: 904ef225a4d3
Create Date: 2026-02-25 12:34:26.177364
Created By: rahul-arcgate

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a16a06a78ad1'
down_revision: Union[str, Sequence[str], None] = '904ef225a4d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_options_id'), table_name='options')
    op.drop_table('options')
    op.add_column('questions', sa.Column('subject_type', sa.String(length=100), nullable=False))
    op.add_column('questions', sa.Column('exam_level', sa.String(length=100), nullable=False))
    op.add_column('questions', sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('questions', sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('questions', sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.alter_column('questions', 'question_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('questions', 'question_text',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('questions', 'image_url',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_foreign_key(None, 'questions', 'users', ['created_by'], ['id'])
    op.drop_column('questions', 'subject')
    op.drop_column('questions', 'difficulty_level')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('difficulty_level', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('questions', sa.Column('subject', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.alter_column('questions', 'image_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('questions', 'question_text',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('questions', 'question_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('questions', 'updated_at')
    op.drop_column('questions', 'created_at')
    op.drop_column('questions', 'options')
    op.drop_column('questions', 'exam_level')
    op.drop_column('questions', 'subject_type')
    op.create_table('options',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('option_label', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('option_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_correct', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('options_question_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('options_pkey'))
    )
    op.create_index(op.f('ix_options_id'), 'options', ['id'], unique=False)
    # ### end Alembic commands ###
