
"""add_auto_assignment_rules

Revision ID: a754d739dea7
Revises: 8e5e9518d410
Create Date: 2026-04-17 12:50:57.419296
Created By: unknown

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a754d739dea7'
down_revision: Union[str, Sequence[str], None] = '8e5e9518d410'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auto_assignment_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('test_level_id', sa.Integer(), nullable=False),
    sa.Column('assigned_date', sa.Date(), nullable=False),
    sa.Column('paper_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['test_level_id'], ['classifications.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('department_id', 'test_level_id', 'assigned_date', name='uq_auto_assignment_rules_dept_level_date')
    )
    op.create_index(op.f('ix_auto_assignment_rules_assigned_date'), 'auto_assignment_rules', ['assigned_date'], unique=False)
    op.create_index(op.f('ix_auto_assignment_rules_department_id'), 'auto_assignment_rules', ['department_id'], unique=False)
    op.create_index(op.f('ix_auto_assignment_rules_id'), 'auto_assignment_rules', ['id'], unique=False)
    op.create_index(op.f('ix_auto_assignment_rules_test_level_id'), 'auto_assignment_rules', ['test_level_id'], unique=False)
    op.add_column('paper_assignments', sa.Column('assignment_source', sa.String(length=50), server_default='MANUAL', nullable=False))
    op.add_column('paper_assignments', sa.Column('auto_rule_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'paper_assignments', 'auto_assignment_rules', ['auto_rule_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'paper_assignments', type_='foreignkey')
    op.drop_column('paper_assignments', 'auto_rule_id')
    op.drop_column('paper_assignments', 'assignment_source')
    op.drop_index(op.f('ix_auto_assignment_rules_test_level_id'), table_name='auto_assignment_rules')
    op.drop_index(op.f('ix_auto_assignment_rules_id'), table_name='auto_assignment_rules')
    op.drop_index(op.f('ix_auto_assignment_rules_department_id'), table_name='auto_assignment_rules')
    op.drop_index(op.f('ix_auto_assignment_rules_assigned_date'), table_name='auto_assignment_rules')
    op.drop_table('auto_assignment_rules')
    # ### end Alembic commands ###
