
"""create_interview_evaluations_table

Revision ID: b8b26792b253
Revises: 28004a445359
Create Date: 2026-04-27 10:59:31.286063
Created By: unknown

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b8b26792b253'
down_revision: Union[str, Sequence[str], None] = '28004a445359'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_evaluations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_lead_id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('round_type', sa.String(length=50), server_default='F2F', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('evaluation_data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('overall_grade', sa.String(length=20), nullable=True),
    sa.Column('final_verdict_id', sa.Integer(), nullable=True),
    sa.Column('comments', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['interview_records.id'], ),
    sa.ForeignKeyConstraint(['final_verdict_id'], ['classifications.id'], ),
    sa.ForeignKeyConstraint(['project_lead_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_evaluations_attempt_id'), 'interview_evaluations', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_interview_evaluations_id'), 'interview_evaluations', ['id'], unique=False)
    op.create_index(op.f('ix_interview_evaluations_project_lead_id'), 'interview_evaluations', ['project_lead_id'], unique=False)
    op.create_index(op.f('ix_interview_evaluations_user_id'), 'interview_evaluations', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interview_evaluations_user_id'), table_name='interview_evaluations')
    op.drop_index(op.f('ix_interview_evaluations_project_lead_id'), table_name='interview_evaluations')
    op.drop_index(op.f('ix_interview_evaluations_id'), table_name='interview_evaluations')
    op.drop_index(op.f('ix_interview_evaluations_attempt_id'), table_name='interview_evaluations')
    op.drop_table('interview_evaluations')
    # ### end Alembic commands ###
