
"""latest_db_changes

Revision ID: bbebf9c48f6f
Revises: 7ce554207c66
Create Date: 2026-03-17 15:35:59.452541
Created By: md-danish-ai

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbebf9c48f6f'
down_revision: Union[str, Sequence[str], None] = '7ce554207c66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('classifications_type_code_key'), 'classifications', type_='unique')
    op.create_unique_constraint('uix_type_code', 'classifications', ['type', 'code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_type_code', 'classifications', type_='unique')
    op.create_unique_constraint(op.f('classifications_type_code_key'), 'classifications', ['type', 'code'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
