"""Add additional_personal_details

Revision ID: c99e0571027a
Revises: a2dee70412de
Create Date: 2026-07-03 17:06:22.722654
Created By: md-danish-ai

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c99e0571027a"
down_revision: Union[str, Sequence[str], None] = "a2dee70412de"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_details",
        sa.Column(
            "additional_personal_details",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_details", "additional_personal_details")
    # ### end Alembic commands ###
