"""add_requires_interview_to_departments

Revision ID: cafd7824de07
Revises: e4f490f8874c
Create Date: 2026-07-31 11:44:33.273997
Created By: md-danish-ai

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cafd7824de07"
down_revision: Union[str, Sequence[str], None] = "e4f490f8874c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("idx_city_district"), table_name="cities")
    op.drop_table("cities")
    op.drop_table("states")
    op.drop_index(op.f("idx_district_state"), table_name="districts")
    op.drop_table("districts")
    op.add_column(
        "departments",
        sa.Column(
            "requires_interview", sa.Boolean(), server_default="true", nullable=False
        ),
    )
    op.drop_index(
        op.f("ix_interview_records_paper_user_status"), table_name="interview_records"
    )
    op.drop_index(
        op.f("ix_paper_assignments_date_attempted"), table_name="paper_assignments"
    )
    op.drop_index(
        op.f("ix_paper_assignments_user_date"), table_name="paper_assignments"
    )
    op.drop_index(op.f("ix_questions_subject_active"), table_name="questions")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_questions_subject_active"),
        "questions",
        ["subject_type", "is_active"],
        unique=False,
    )
    op.create_index(
        op.f("ix_paper_assignments_user_date"),
        "paper_assignments",
        ["user_id", "assigned_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_paper_assignments_date_attempted"),
        "paper_assignments",
        ["assigned_date", "is_attempted"],
        unique=False,
    )
    op.create_index(
        op.f("ix_interview_records_paper_user_status"),
        "interview_records",
        ["paper_id", "user_id", "status"],
        unique=False,
    )
    op.drop_column("departments", "requires_interview")
    op.create_table(
        "districts",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("state_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(length=150), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["state_id"],
            ["states.id"],
            name=op.f("districts_state_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("districts_pkey")),
    )
    op.create_index(op.f("idx_district_state"), "districts", ["state_id"], unique=False)
    op.create_table(
        "states",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("code", sa.VARCHAR(length=5), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("states_pkey")),
        sa.UniqueConstraint(
            "code",
            name=op.f("states_code_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_table(
        "cities",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("district_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(length=150), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["district_id"],
            ["districts.id"],
            name=op.f("cities_district_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("cities_pkey")),
    )
    op.create_index(op.f("idx_city_district"), "cities", ["district_id"], unique=False)
    # ### end Alembic commands ###
