
"""add manual_marks to answers

Revision ID: d52705930a5e
Revises: 3f9d60802d28
Create Date: 2026-03-25 18:58:09.069384
Created By: unknown

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd52705930a5e'
down_revision: Union[str, Sequence[str], None] = '3f9d60802d28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_attempt_answers', sa.Column('manual_marks', sa.Numeric(precision=10, scale=2), nullable=True))
    op.alter_column('paper_assignments', 'is_attempted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('paper_assignments', 'is_attempted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_column('interview_attempt_answers', 'manual_marks')
    # ### end Alembic commands ###
