
"""add_new_columns_to_papers

Revision ID: e4adefe9fcb0
Revises: e09debccb6dd
Create Date: 2026-03-13 11:50:24.332589
Created By: md-danish-ai

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4adefe9fcb0'
down_revision: Union[str, Sequence[str], None] = 'e09debccb6dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('papers', sa.Column('paper_name', sa.String(length=255), nullable=False))
    op.add_column('papers', sa.Column('description', sa.String(length=1000), nullable=True))
    op.add_column('papers', sa.Column('department_id', sa.Integer(), nullable=False))
    op.add_column('papers', sa.Column('test_level_id', sa.Integer(), nullable=False))
    op.add_column('papers', sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.create_foreign_key(None, 'papers', 'departments', ['department_id'], ['id'])
    op.create_foreign_key(None, 'papers', 'classifications', ['test_level_id'], ['id'])
    op.drop_column('papers', 'level')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('papers', sa.Column('level', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'papers', type_='foreignkey')
    op.drop_constraint(None, 'papers', type_='foreignkey')
    op.drop_column('papers', 'updated_at')
    op.drop_column('papers', 'test_level_id')
    op.drop_column('papers', 'department_id')
    op.drop_column('papers', 'description')
    op.drop_column('papers', 'paper_name')
    # ### end Alembic commands ###
