"""Add match_details to duplicate_user_matches

Revision ID: e887446c317b
Revises: 8255fabdad40
Create Date: 2026-03-10 05:59:44.399392
Created By: unknown

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e887446c317b"
down_revision: Union[str, Sequence[str], None] = "8255fabdad40"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "duplicate_user_matches",
        sa.Column(
            "match_details", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("duplicate_user_matches", "match_details")
    # ### end Alembic commands ###
