
"""added answers and classification table

Revision ID: e9c4f33e04b9
Revises: a16a06a78ad1
Create Date: 2026-02-25 16:26:08.792192
Created By: rahul-arcgate

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e9c4f33e04b9'
down_revision: Union[str, Sequence[str], None] = 'a16a06a78ad1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classifications_id'), 'classifications', ['id'], unique=False)
    op.create_table('user_details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('personal_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('family_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_of_information', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('education_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('work_experience_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('other_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_submitted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_details_id'), 'user_details', ['id'], unique=False)
    op.create_table('question_answers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id')
    )
    op.create_index(op.f('ix_question_answers_id'), 'question_answers', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_question_answers_id'), table_name='question_answers')
    op.drop_table('question_answers')
    op.drop_index(op.f('ix_user_details_id'), table_name='user_details')
    op.drop_table('user_details')
    op.drop_index(op.f('ix_classifications_id'), table_name='classifications')
    op.drop_table('classifications')
    # ### end Alembic commands ###
