# ruff: noqa
# Auto-generated seed file from database on 2026-08-13 16:24:01
import sys
import os
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

true = True
false = False
null = None

from app.database.db import SessionLocal
from app.questions.models import Question
from app.answer.models import QuestionAnswer
from sqlalchemy.orm.attributes import flag_modified

QUESTIONS_DATA = [
    {
        "id": 1,
        "question_type": "MULTIPLE_CHOICE",
        "subject_type": "APTITUDE",
        "exam_level": "FRESHER",
        "question_text": "The sum of the ages of a mother and her daughter is 50 years. Five years ago, the mother's age was four times the daughter's age. What will be the daughter's age after 5 years?",
        "image_url": null,
        "passage": null,
        "marks": 1,
        "options": [{"image_url": null, "is_correct": false, "option_text": "15 years", "option_label": "A"}, {"image_url": null, "is_correct": true, "option_text": "18 years", "option_label": "B"}, {"image_url": null, "is_correct": false, "option_text": "20 years", "option_label": "C"}, {"image_url": null, "is_correct": false, "option_text": "23 years", "option_label": "D"}],
        "is_active": true,
        "created_by": 1,
        "answer_text": "B",
        "explanation": "nan"
    },
    {
        "id": 2,
        "question_type": "MULTIPLE_CHOICE",
        "subject_type": "APTITUDE",
        "exam_level": "FRESHER",
        "question_text": "A museum has an average of 480 visitors on Wednesdays and 210 on other days. The average number of visitors per day in a month of 30 days beginning with a Wednesday is:",
        "image_url": null,
        "passage": null,
        "marks": 1,
        "options": [{"image_url": null, "is_correct": false, "option_text": "230", "option_label": "A"}, {"image_url": null, "is_correct": false, "option_text": "245", "option_label": "B"}, {"image_url": null, "is_correct": true, "option_text": "255", "option_label": "C"}, {"image_url": null, "is_correct": false, "option_text": "260", "option_label": "D"}],
        "is_active": true,
        "created_by": 1,
        "answer_text": "C",
        "explanation": "nan"
    },
    {
        "id": 3,
        "question_type": "MULTIPLE_CHOICE",
        "subject_type": "APTITUDE",
        "exam_level": "FRESHER",
        "question_text": "A trader buys a bicycle for Rs. 1,800 in cash and sells it for Rs. 2,090 at a credit of 1 year. If the rate of interest is 10% per annum, the trader gains:",
        "image_url": null,
        "passage": null,
        "marks": 1,
        "options": [{"image_url": null, "is_correct": false, "option_text": "Rs. 80", "option_label": "A"}, {"image_url": null, "is_correct": true, "option_text": "Rs. 100", "option_label": "B"}, {"image_url": null, "is_correct": false, "option_text": "Rs. 120", "option_label": "C"}, {"image_url": null, "is_correct": false, "option_text": "Rs. 150", "option_label": "D"}],
        "is_active": true,
        "created_by": 1,
        "answer_text": "B",
        "explanation": "nan"
    },
    {
        "id": 4,
        "question_type": "MULTIPLE_CHOICE",
        "subject_type": "APTITUDE",
        "exam_level": "FRESHER",
        "question_text": "The average weight of 10 persons increases by 3 kg when a new person replaces one of them weighing 60 kg. What is the weight of the new person?",
        "image_url": null,
        "passage": null,
        "marks": 1,
        "options": [{"image_url": null, "is_correct": false, "option_text": "85 kg", "option_label": "A"}, {"image_url": null, "is_correct": false, "option_text": "88 kg", "option_label": "B"}, {"image_url": null, "is_correct": true, "option_text": "90 kg", "option_label": "C"}, {"image_url": null, "is_correct": false, "option_text": "95 kg", "option_label": "D"}],
        "is_active": true,
        "created_by": 1,
        "answer_text": "C",
        "explanation": "nan"
    },
    {
        "id": 5,
        "question_type": "MULTIPLE_CHOICE",
        "subject_type": "APTITUDE",
        "exam_level": "FRESHER",
        "question_text": "Pick the odd one out:",
        "image_url": null,
        "passage": null,
        "marks": 1,
        "options": [{"image_url": null, "is_correct": false, "option_text": "Sparrow", "option_label": "A"}, {"image_url": null, "is_correct": false, "option_text": "Eagle", "option_label": "B"}, {"image_url": null, "is_correct": true, "option_text": "Ostrich", "option_label": "C"}, {"image_url": null, "is_correct": false, "option_text": "Pigeon", "option_label": "D"}],
        "is_active": true,
        "created_by": 1,
        "answer_text": "C",
        "explanation": "nan"
    },
    {
        "id": 6,
        "question_type": "MULTIPLE_CHOICE",
        "subject_type": "APTITUDE",
        "exam_level": "FRESHER",
        "question_text": "Pick the odd one out:",
        "image_url": null,
        "passage": null,
        "marks": 1,
        "options": [{"image_url": null, "is_correct": false, "option_text": "BDFH", "option_label": "A"}, {"image_url": null, "is_correct": false, "option_text": "CEGI", "option_label": "B"}, {"image_url": null, "is_correct": true, "option_text": "ILNP", "option_label": "C"}, {"image_url": null, "is_correct": false, "option_text": "MOQS", "option_label": "D"}],
        "is_active": true,
        "created_by": 1,
        "answer_text": "C",
        "explanation": "nan"
    },
    {
        "id": 7,
        "question_type": "MULTIPLE_CHOICE",
        "subject_type": "APTITUDE",
        "exam_level": "FRESHER",
        "question_text": "Look at this series: 15, 16, 31, 47, 78, ... What number should come next?",
        "image_url": null,
        "passage": null,
        "marks": 1,
        "options": [{"image_url": null, "is_correct": false, "option_text": "115", "option_label": "A"}, {"image_url": null, "is_correct": false, "option_text": "120", "option_label": "B"}, {"image_url": null, "is_correct": true, "option_text": "125", "option_label": "C"}, {"image_url": null, "is_correct": false, "option_text": "130", "option_label": "D"}],
        "is_active": true,
        "created_by": 1,
        "answer_text": "C",
        "explanation": "nan"
    },
    {
        "id": 8,
        "question_type": "MULTIPLE_CHOICE",
        "subject_type": "APTITUDE",
        "exam_level": "FRESHER",
        "question_text": "Q is as much younger than R as he is older than T. If the sum of the ages of R and T is 60 years, what is definitely the difference between R and Q's age?",
        "image_url": null,
        "passage": null,
        "marks": 1,
        "options": [{"image_url": null, "is_correct": false, "option_text": "1 year", "option_label": "A"}, {"image_url": null, "is_correct": false, "option_text": "2 years", "option_label": "B"}, {"image_url": null, "is_correct": false, "option_text": "30 years", "option_label": "C"}, {"image_url": null, "is_correct": true, "option_text": "Data inadequate", "option_label": "D"}],
        "is_active": true,
        "created_by": 1,
        "answer_text": "D",
        "explanation": "nan"
    },
    {
        "id": 9,
        "question_type": "MULTIPLE_CHOICE",
        "subject_type": "APTITUDE",
        "exam_level": "FRESHER",
        "question_text": "Ravi wants to buy 400 notebooks for his store. He gets the first 250 notebooks for $2,000. The next 150 notebooks cost $5 each. If a 10% discount is applied to the total cost, what is the total cost of the notebooks?",
        "image_url": null,
        "passage": null,
        "marks": 1,
        "options": [{"image_url": null, "is_correct": true, "option_text": "$2,475", "option_label": "A"}, {"image_url": null, "is_correct": false, "option_text": "$2,500", "option_label": "B"}, {"image_url": null, "is_correct": false, "option_text": "$2,600", "option_label": "C"}, {"image_url": null, "is_correct": false, "option_text": "$2,700", "option_label": "D"}],
        "is_active": true,
        "created_by": 1,
        "answer_text": "A",
        "explanation": "nan"
    },
    {
        "id": 10,
        "question_type": "MULTIPLE_CHOICE",
        "subject_type": "APTITUDE",
        "exam_level": "FRESHER",
        "question_text": "A is three years older than B, who is twice as old as C. If the total of the ages of A, B and C is 48, how old is B?",
        "image_url": null,
        "passage": null,
        "marks": 1,
        "options": [{"image_url": null, "is_correct": false, "option_text": "16", "option_label": "A"}, {"image_url": null, "is_correct": true, "option_text": "18", "option_label": "B"}, {"image_url": null, "is_correct": false, "option_text": "20", "option_label": "C"}, {"image_url": null, "is_correct": false, "option_text": "22", "option_label": "D"}],
        "is_active": true,
        "created_by": 1,
        "answer_text": "B",
        "explanation": "nan"
    },
    {
        "id": 11,
        "question_type": "MULTIPLE_CHOICE",
        "subject_type": "APTITUDE",
        "exam_level": "FRESHER",
        "question_text": "Sam purchased 8 dozens of pens at the rate of Rs. 480 per dozen. He sold each one of them at the rate of Rs. 45. What was his percentage profit?",
        "image_url": null,
        "passage": null,
        "marks": 1,
        "options": [{"image_url": null, "is_correct": false, "option_text": "0.1", "option_label": "A"}, {"image_url": null, "is_correct": true, "option_text": "0.125", "option_label": "B"}, {"image_url": null, "is_correct": false, "option_text": "0.15", "option_label": "C"}, {"image_url": null, "is_correct": false, "option_text": "0.08", "option_label": "D"}],
        "is_active": true,
        "created_by": 1,
        "answer_text": "B",
        "explanation": "nan"
    },
    {
        "id": 12,
        "question_type": "MULTIPLE_CHOICE",
        "subject_type": "APTITUDE",
        "exam_level": "FRESHER",
        "question_text": "Rahul walks 9 km to the north, then turns and walks 12 km to the east. How far is he from his starting point?",
        "image_url": null,
        "passage": null,
        "marks": 1,
        "options": [{"image_url": null, "is_correct": true, "option_text": "15 km", "option_label": "A"}, {"image_url": null, "is_correct": false, "option_text": "18 km", "option_label": "B"}, {"image_url": null, "is_correct": false, "option_text": "20 km", "option_label": "C"}, {"image_url": null, "is_correct": false, "option_text": "21 km", "option_label": "D"}],
        "is_active": true,
        "created_by": 1,
        "answer_text": "A",
        "explanation": "nan"
    },
    {
        "id": 13,
        "question_type": "MULTIPLE_CHOICE",
        "subject_type": "APTITUDE",
        "exam_level": "FRESHER",
        "question_text": "P told Q, 'The boy I met yesterday was the only son of the father-in-law of my sister's husband.' How is the boy related to P?",
        "image_url": null,
        "passage": null,
        "marks": 1,
        "options": [{"image_url": null, "is_correct": true, "option_text": "Brother", "option_label": "A"}, {"image_url": null, "is_correct": false, "option_text": "Nephew", "option_label": "B"}, {"image_url": null, "is_correct": false, "option_text": "Cousin", "option_label": "C"}, {"image_url": null, "is_correct": false, "option_text": "Son", "option_label": "D"}],
        "is_active": true,
        "created_by": 1,
        "answer_text": "A",
        "explanation": "nan"
    },
    {
        "id": 14,
        "question_type": "MULTIPLE_CHOICE",
        "subject_type": "APTITUDE",
        "exam_level": "FRESHER",
        "question_text": "The sum of the digits of a 2-digit number is 11. If we add 45 to the number, the new number obtained is formed by interchanging the digits. What is the number?",
        "image_url": null,
        "passage": null,
        "marks": 1,
        "options": [{"image_url": null, "is_correct": true, "option_text": "x = 3 and y = 8", "option_label": "A"}, {"image_url": null, "is_correct": false, "option_text": "x = 4 and y = 7", "option_label": "B"}, {"image_url": null, "is_correct": false, "option_text": "x = 5 and y = 6", "option_label": "C"}, {"image_url": null, "is_correct": false, "option_text": "x = 2 and y = 9", "option_label": "D"}],
        "is_active": true,
        "created_by": 1,
        "answer_text": "A",
        "explanation": "nan"
    },
    {
        "id": 15,
        "question_type": "MULTIPLE_CHOICE",
        "subject_type": "APTITUDE",
        "exam_level": "FRESHER",
        "question_text": "In the first 15 overs of a cricket match, the run rate was only 3.2. What should be the run rate in the remaining 35 overs to reach a target of 272 runs?",
        "image_url": null,
        "passage": null,
        "marks": 1,
        "options": [{"image_url": null, "is_correct": false, "option_text": "6", "option_label": "A"}, {"image_url": null, "is_correct": false, "option_text": "6.2", "option_label": "B"}, {"image_url": null, "is_correct": true, "option_text": "6.4", "option_label": "C"}, {"image_url": null, "is_correct": false, "option_text": "6.6", "option_label": "D"}],
        "is_active": true,
        "created_by": 1,
        "answer_text": "C",
        "explanation": "nan"
    },
    {
        "id": 16,
        "question_type": "MULTIPLE_CHOICE",
        "subject_type": "APTITUDE",
        "exam_level": "FRESHER",
        "question_text": "A mother is three times as old as her son. If 15 years ago the age of the mother was six times the age of the son, what is the present age of the mother?",
        "image_url": null,
        "passage": null,
        "marks": 1,
        "options": [{"image_url": null, "is_correct": false, "option_text": "70 years", "option_label": "A"}, {"image_url": null, "is_correct": false, "option_text": "72 years", "option_label": "B"}, {"image_url": null, "is_correct": true, "option_text": "75 years", "option_label": "C"}, {"image_url": null, "is_correct": false, "option_text": "78 years", "option_label": "D"}],
        "is_active": true,
        "created_by": 1,
        "answer_text": "C",
        "explanation": "nan"
    },
    {
        "id": 17,
        "question_type": "MULTIPLE_CHOICE",
        "subject_type": "INDUSTRY_AWARENESS",
        "exam_level": "FRESHER",
        "question_text": "A credit card is used for:",
        "image_url": null,
        "passage": null,
        "marks": 1,
        "options": [{"image_url": null, "is_correct": false, "option_text": "Withdrawing money directly from a savings account", "option_label": "A"}, {"image_url": null, "is_correct": true, "option_text": "Borrowing money from the bank up to a set limit", "option_label": "B"}, {"image_url": null, "is_correct": false, "option_text": "Transferring money instantly between two banks free of cost", "option_label": "C"}, {"image_url": null, "is_correct": false, "option_text": "None of the above", "option_label": "D"}],
        "is_active": true,
        "created_by": 1,
        "answer_text": "B",
        "explanation": "nan"
    },
    {
        "id": 18,
        "question_type": "MULTIPLE_CHOICE",
        "subject_type": "INDUSTRY_AWARENESS",
        "exam_level": "FRESHER",
        "question_text": "Which of the following is not an online food delivery platform?",
        "image_url": null,
        "passage": null,
        "marks": 1,
        "options": [{"image_url": null, "is_correct": false, "option_text": "Zomato", "option_label": "A"}, {"image_url": null, "is_correct": false, "option_text": "Swiggy", "option_label": "B"}, {"image_url": null, "is_correct": false, "option_text": "DoorDash", "option_label": "C"}, {"image_url": null, "is_correct": true, "option_text": "None of these", "option_label": "D"}],
        "is_active": true,
        "created_by": 1,
        "answer_text": "D",
        "explanation": "nan"
    },
    {
        "id": 19,
        "question_type": "MULTIPLE_CHOICE",
        "subject_type": "INDUSTRY_AWARENESS",
        "exam_level": "FRESHER",
        "question_text": "Pick the odd one out:",
        "image_url": null,
        "passage": null,
        "marks": 1,
        "options": [{"image_url": null, "is_correct": false, "option_text": "Croissant", "option_label": "A"}, {"image_url": null, "is_correct": false, "option_text": "Bagel", "option_label": "B"}, {"image_url": null, "is_correct": false, "option_text": "Baguette", "option_label": "C"}, {"image_url": null, "is_correct": true, "option_text": "Risotto", "option_label": "D"}],
        "is_active": true,
        "created_by": 1,
        "answer_text": "D",
        "explanation": "nan"
    },
    {
        "id": 20,
        "question_type": "MULTIPLE_CHOICE",
        "subject_type": "INDUSTRY_AWARENESS",
        "exam_level": "FRESHER",
        "question_text": "A discounted meal deal specially targeted at families is called:",
        "image_url": null,
        "passage": null,
        "marks": 1,
        "options": [{"image_url": null, "is_correct": false, "option_text": "Kid's Meal", "option_label": "A"}, {"image_url": null, "is_correct": true, "option_text": "Family Combo", "option_label": "B"}, {"image_url": null, "is_correct": false, "option_text": "Solo Meal", "option_label": "C"}, {"image_url": null, "is_correct": false, "option_text": "Executive Meal", "option_label": "D"}],
        "is_active": true,
        "created_by": 1,
        "answer_text": "B",
        "explanation": "nan"
    },
    {
        "id": 21,
        "question_type": "MULTIPLE_CHOICE",
        "subject_type": "INDUSTRY_AWARENESS",
        "exam_level": "FRESHER",
        "question_text": "An Italian sparkling wine is called:",
        "image_url": null,
        "passage": null,
        "marks": 1,
        "options": [{"image_url": null, "is_correct": true, "option_text": "Prosecco", "option_label": "A"}, {"image_url": null, "is_correct": false, "option_text": "Sake", "option_label": "B"}, {"image_url": null, "is_correct": false, "option_text": "Whisky", "option_label": "C"}, {"image_url": null, "is_correct": false, "option_text": "Vodka", "option_label": "D"}],
        "is_active": true,
        "created_by": 1,
        "answer_text": "A",
        "explanation": "nan"
    },
    {
        "id": 22,
        "question_type": "MULTIPLE_CHOICE",
        "subject_type": "INDUSTRY_AWARENESS",
        "exam_level": "FRESHER",
        "question_text": "The tagline 'I'm Lovin' It' is associated with which brand?",
        "image_url": null,
        "passage": null,
        "marks": 1,
        "options": [{"image_url": null, "is_correct": false, "option_text": "Burger King", "option_label": "A"}, {"image_url": null, "is_correct": false, "option_text": "KFC", "option_label": "B"}, {"image_url": null, "is_correct": true, "option_text": "McDonald's", "option_label": "C"}, {"image_url": null, "is_correct": false, "option_text": "Subway", "option_label": "D"}],
        "is_active": true,
        "created_by": 1,
        "answer_text": "C",
        "explanation": "nan"
    },
    {
        "id": 23,
        "question_type": "MULTIPLE_CHOICE",
        "subject_type": "INDUSTRY_AWARENESS",
        "exam_level": "FRESHER",
        "question_text": "The buying and selling of goods over the internet is called:",
        "image_url": null,
        "passage": null,
        "marks": 1,
        "options": [{"image_url": null, "is_correct": false, "option_text": "E-governance", "option_label": "A"}, {"image_url": null, "is_correct": true, "option_text": "E-commerce", "option_label": "B"}, {"image_url": null, "is_correct": false, "option_text": "E-marketing", "option_label": "C"}, {"image_url": null, "is_correct": false, "option_text": "E-procurement", "option_label": "D"}],
        "is_active": true,
        "created_by": 1,
        "answer_text": "B",
        "explanation": "nan"
    },
    {
        "id": 24,
        "question_type": "MULTIPLE_CHOICE",
        "subject_type": "INDUSTRY_AWARENESS",
        "exam_level": "FRESHER",
        "question_text": "The most cost-effective method of delivering digital goods (like e-books) is:",
        "image_url": null,
        "passage": null,
        "marks": 1,
        "options": [{"image_url": null, "is_correct": false, "option_text": "Postal delivery", "option_label": "A"}, {"image_url": null, "is_correct": true, "option_text": "Electronic/digital delivery", "option_label": "B"}, {"image_url": null, "is_correct": false, "option_text": "Courier service", "option_label": "C"}, {"image_url": null, "is_correct": false, "option_text": "None of the above", "option_label": "D"}],
        "is_active": true,
        "created_by": 1,
        "answer_text": "B",
        "explanation": "nan"
    },
    {
        "id": 25,
        "question_type": "MULTIPLE_CHOICE",
        "subject_type": "INDUSTRY_AWARENESS",
        "exam_level": "FRESHER",
        "question_text": "Retailers can never earn any margin on shipping and handling charges.",
        "image_url": null,
        "passage": null,
        "marks": 1,
        "options": [{"image_url": null, "is_correct": false, "option_text": "True", "option_label": "A"}, {"image_url": null, "is_correct": true, "option_text": "False", "option_label": "B"}],
        "is_active": true,
        "created_by": 1,
        "answer_text": "B",
        "explanation": "nan"
    },
    {
        "id": 26,
        "question_type": "MULTIPLE_CHOICE",
        "subject_type": "INDUSTRY_AWARENESS",
        "exam_level": "FRESHER",
        "question_text": "Which among the following is not an example of e-commerce?",
        "image_url": null,
        "passage": null,
        "marks": 1,
        "options": [{"image_url": null, "is_correct": false, "option_text": "Amazon", "option_label": "A"}, {"image_url": null, "is_correct": false, "option_text": "Nykaa", "option_label": "B"}, {"image_url": null, "is_correct": false, "option_text": "BigBasket", "option_label": "C"}, {"image_url": null, "is_correct": true, "option_text": "A railway station ticket counter", "option_label": "D"}],
        "is_active": true,
        "created_by": 1,
        "answer_text": "D",
        "explanation": "nan"
    },
    {
        "id": 27,
        "question_type": "MULTIPLE_CHOICE",
        "subject_type": "INDUSTRY_AWARENESS",
        "exam_level": "FRESHER",
        "question_text": "'Early bird' offers in a restaurant typically mean:",
        "image_url": null,
        "passage": null,
        "marks": 1,
        "options": [{"image_url": null, "is_correct": true, "option_text": "A discounted price offered before peak hours", "option_label": "A"}, {"image_url": null, "is_correct": false, "option_text": "A time when the restaurant is closed", "option_label": "B"}, {"image_url": null, "is_correct": false, "option_text": "A special menu only for breakfast", "option_label": "C"}, {"image_url": null, "is_correct": false, "option_text": "None of the above", "option_label": "D"}],
        "is_active": true,
        "created_by": 1,
        "answer_text": "A",
        "explanation": "nan"
    },
    {
        "id": 28,
        "question_type": "MULTIPLE_CHOICE",
        "subject_type": "INDUSTRY_AWARENESS",
        "exam_level": "FRESHER",
        "question_text": "Hollandaise, Béchamel and Marinara are types of:",
        "image_url": null,
        "passage": null,
        "marks": 1,
        "options": [{"image_url": null, "is_correct": true, "option_text": "Sauces", "option_label": "A"}, {"image_url": null, "is_correct": false, "option_text": "Breads", "option_label": "B"}, {"image_url": null, "is_correct": false, "option_text": "Desserts", "option_label": "C"}, {"image_url": null, "is_correct": false, "option_text": "Beverages", "option_label": "D"}],
        "is_active": true,
        "created_by": 1,
        "answer_text": "A",
        "explanation": "nan"
    },
    {
        "id": 29,
        "question_type": "MULTIPLE_CHOICE",
        "subject_type": "INDUSTRY_AWARENESS",
        "exam_level": "FRESHER",
        "question_text": "Which country is most associated with Sushi?",
        "image_url": null,
        "passage": null,
        "marks": 1,
        "options": [{"image_url": null, "is_correct": false, "option_text": "China", "option_label": "A"}, {"image_url": null, "is_correct": true, "option_text": "Japan", "option_label": "B"}, {"image_url": null, "is_correct": false, "option_text": "Thailand", "option_label": "C"}, {"image_url": null, "is_correct": false, "option_text": "Korea", "option_label": "D"}],
        "is_active": true,
        "created_by": 1,
        "answer_text": "B",
        "explanation": "nan"
    },
    {
        "id": 30,
        "question_type": "MULTIPLE_CHOICE",
        "subject_type": "INDUSTRY_AWARENESS",
        "exam_level": "FRESHER",
        "question_text": "What is a 'fortified wine'?",
        "image_url": null,
        "passage": null,
        "marks": 1,
        "options": [{"image_url": null, "is_correct": true, "option_text": "A wine with added distilled spirit, increasing its alcohol content", "option_label": "A"}, {"image_url": null, "is_correct": false, "option_text": "A wine stored in a fortified cellar", "option_label": "B"}, {"image_url": null, "is_correct": false, "option_text": "A wine made only from fortified grapes", "option_label": "C"}, {"image_url": null, "is_correct": false, "option_text": "None of the above", "option_label": "D"}],
        "is_active": true,
        "created_by": 1,
        "answer_text": "A",
        "explanation": "nan"
    },
    {
        "id": 31,
        "question_type": "MULTIPLE_CHOICE",
        "subject_type": "INDUSTRY_AWARENESS",
        "exam_level": "FRESHER",
        "question_text": "What does 'Cashback' typically mean in retail/e-commerce transactions?",
        "image_url": null,
        "passage": null,
        "marks": 1,
        "options": [{"image_url": null, "is_correct": true, "option_text": "A percentage of the purchase amount returned to the buyer after the transaction", "option_label": "A"}, {"image_url": null, "is_correct": false, "option_text": "An additional fee charged for using cash", "option_label": "B"}, {"image_url": null, "is_correct": false, "option_text": "A loan given at the time of purchase", "option_label": "C"}, {"image_url": null, "is_correct": false, "option_text": "None of these", "option_label": "D"}],
        "is_active": true,
        "created_by": 1,
        "answer_text": "A",
        "explanation": "nan"
    },
    {
        "id": 32,
        "question_type": "MULTIPLE_CHOICE",
        "subject_type": "INDUSTRY_AWARENESS",
        "exam_level": "FRESHER",
        "question_text": "The term 'table d'hôte' refers to:",
        "image_url": null,
        "passage": null,
        "marks": 1,
        "options": [{"image_url": null, "is_correct": true, "option_text": "A fixed-price meal with limited choices offered at a set price", "option_label": "A"}, {"image_url": null, "is_correct": false, "option_text": "A meal that must be custom ordered", "option_label": "B"}, {"image_url": null, "is_correct": false, "option_text": "A free meal offered by the host", "option_label": "C"}, {"image_url": null, "is_correct": false, "option_text": "None of the above", "option_label": "D"}],
        "is_active": true,
        "created_by": 1,
        "answer_text": "A",
        "explanation": "nan"
    },
    {
        "id": 33,
        "question_type": "MULTIPLE_CHOICE",
        "subject_type": "ENGLISH_GRAMMAR",
        "exam_level": "FRESHER",
        "question_text": "By the time she arrives, we ______ dinner.",
        "image_url": null,
        "passage": null,
        "marks": 1,
        "options": [{"image_url": null, "is_correct": false, "option_text": "will finish", "option_label": "A"}, {"image_url": null, "is_correct": true, "option_text": "will have finished", "option_label": "B"}, {"image_url": null, "is_correct": false, "option_text": "finish", "option_label": "C"}, {"image_url": null, "is_correct": false, "option_text": "are finishing", "option_label": "D"}],
        "is_active": true,
        "created_by": 1,
        "answer_text": "B",
        "explanation": "nan"
    },
    {
        "id": 34,
        "question_type": "MULTIPLE_CHOICE",
        "subject_type": "ENGLISH_GRAMMAR",
        "exam_level": "FRESHER",
        "question_text": "He ______ hardly speak when he arrived, he was so exhausted.",
        "image_url": null,
        "passage": null,
        "marks": 1,
        "options": [{"image_url": null, "is_correct": true, "option_text": "could", "option_label": "A"}, {"image_url": null, "is_correct": false, "option_text": "can", "option_label": "B"}, {"image_url": null, "is_correct": false, "option_text": "would", "option_label": "C"}, {"image_url": null, "is_correct": false, "option_text": "should", "option_label": "D"}],
        "is_active": true,
        "created_by": 1,
        "answer_text": "A",
        "explanation": "nan"
    },
    {
        "id": 35,
        "question_type": "MULTIPLE_CHOICE",
        "subject_type": "ENGLISH_GRAMMAR",
        "exam_level": "FRESHER",
        "question_text": "Synonym of 'abundant' is ______.",
        "image_url": null,
        "passage": null,
        "marks": 1,
        "options": [{"image_url": null, "is_correct": false, "option_text": "Scarce", "option_label": "A"}, {"image_url": null, "is_correct": true, "option_text": "Plentiful", "option_label": "B"}, {"image_url": null, "is_correct": false, "option_text": "Meager", "option_label": "C"}, {"image_url": null, "is_correct": false, "option_text": "Sparse", "option_label": "D"}],
        "is_active": true,
        "created_by": 1,
        "answer_text": "B",
        "explanation": "nan"
    },
    {
        "id": 36,
        "question_type": "MULTIPLE_CHOICE",
        "subject_type": "ENGLISH_GRAMMAR",
        "exam_level": "FRESHER",
        "question_text": "I think my proposal ______ by the committee already.",
        "image_url": null,
        "passage": null,
        "marks": 1,
        "options": [{"image_url": null, "is_correct": false, "option_text": "rejecting", "option_label": "A"}, {"image_url": null, "is_correct": false, "option_text": "is rejected", "option_label": "B"}, {"image_url": null, "is_correct": false, "option_text": "has been rejected", "option_label": "C"}, {"image_url": null, "is_correct": true, "option_text": "Either B or C", "option_label": "D"}],
        "is_active": true,
        "created_by": 1,
        "answer_text": "D",
        "explanation": "nan"
    },
    {
        "id": 37,
        "question_type": "MULTIPLE_CHOICE",
        "subject_type": "ENGLISH_GRAMMAR",
        "exam_level": "FRESHER",
        "question_text": "I ______ Sarah last week and she told me she was moving abroad.",
        "image_url": null,
        "passage": null,
        "marks": 1,
        "options": [{"image_url": null, "is_correct": false, "option_text": "have met", "option_label": "A"}, {"image_url": null, "is_correct": false, "option_text": "had meet", "option_label": "B"}, {"image_url": null, "is_correct": true, "option_text": "met", "option_label": "C"}, {"image_url": null, "is_correct": false, "option_text": "meet", "option_label": "D"}],
        "is_active": true,
        "created_by": 1,
        "answer_text": "C",
        "explanation": "nan"
    },
    {
        "id": 38,
        "question_type": "MULTIPLE_CHOICE",
        "subject_type": "ENGLISH_GRAMMAR",
        "exam_level": "FRESHER",
        "question_text": "She ______ coffee in the morning these days.",
        "image_url": null,
        "passage": null,
        "marks": 1,
        "options": [{"image_url": null, "is_correct": false, "option_text": "had never drink", "option_label": "A"}, {"image_url": null, "is_correct": false, "option_text": "has never drink", "option_label": "B"}, {"image_url": null, "is_correct": true, "option_text": "never drinks", "option_label": "C"}, {"image_url": null, "is_correct": false, "option_text": "Never she drinks", "option_label": "D"}],
        "is_active": true,
        "created_by": 1,
        "answer_text": "C",
        "explanation": "nan"
    },
    {
        "id": 39,
        "question_type": "MULTIPLE_CHOICE",
        "subject_type": "ENGLISH_GRAMMAR",
        "exam_level": "FRESHER",
        "question_text": "______ to travel abroad one day?",
        "image_url": null,
        "passage": null,
        "marks": 1,
        "options": [{"image_url": null, "is_correct": false, "option_text": "Have you wish to", "option_label": "A"}, {"image_url": null, "is_correct": true, "option_text": "Would you like to", "option_label": "B"}, {"image_url": null, "is_correct": false, "option_text": "Do you wish to", "option_label": "C"}, {"image_url": null, "is_correct": false, "option_text": "Will you wish to", "option_label": "D"}],
        "is_active": true,
        "created_by": 1,
        "answer_text": "B",
        "explanation": "nan"
    },
    {
        "id": 40,
        "question_type": "SUBJECTIVE",
        "subject_type": "WRITTEN",
        "exam_level": "FRESHER",
        "question_text": "Sincerity",
        "image_url": null,
        "passage": null,
        "marks": 4,
        "options": [],
        "is_active": true,
        "created_by": 1,
        "answer_text": "Sincerity",
        "explanation": "Sincerity"
    },
    {
        "id": 41,
        "question_type": "SUBJECTIVE",
        "subject_type": "WRITTEN",
        "exam_level": "FRESHER",
        "question_text": "Fortunate",
        "image_url": null,
        "passage": null,
        "marks": 4,
        "options": [],
        "is_active": true,
        "created_by": 1,
        "answer_text": "Fortunate",
        "explanation": "Fortunate"
    },
    {
        "id": 42,
        "question_type": "SUBJECTIVE",
        "subject_type": "WRITTEN",
        "exam_level": "FRESHER",
        "question_text": "Beyond",
        "image_url": null,
        "passage": null,
        "marks": 4,
        "options": [],
        "is_active": true,
        "created_by": 1,
        "answer_text": "Beyond",
        "explanation": "Beyond"
    },
    {
        "id": 43,
        "question_type": "SUBJECTIVE",
        "subject_type": "WRITTEN",
        "exam_level": "FRESHER",
        "question_text": "Incidence",
        "image_url": null,
        "passage": null,
        "marks": 4,
        "options": [],
        "is_active": true,
        "created_by": 1,
        "answer_text": "Incidence",
        "explanation": "Incidence"
    },
    {
        "id": 44,
        "question_type": "SUBJECTIVE",
        "subject_type": "WRITTEN",
        "exam_level": "FRESHER",
        "question_text": "Argument",
        "image_url": null,
        "passage": null,
        "marks": 4,
        "options": [],
        "is_active": true,
        "created_by": 1,
        "answer_text": "Argument",
        "explanation": "Argument"
    },
    {
        "id": 45,
        "question_type": "SUBJECTIVE",
        "subject_type": "WRITTEN",
        "exam_level": "FRESHER",
        "question_text": "Historically",
        "image_url": null,
        "passage": null,
        "marks": 4,
        "options": [],
        "is_active": true,
        "created_by": 1,
        "answer_text": "Historic",
        "explanation": "Historic"
    },
    {
        "id": 46,
        "question_type": "SUBJECTIVE",
        "subject_type": "WRITTEN",
        "exam_level": "FRESHER",
        "question_text": "Essential",
        "image_url": null,
        "passage": null,
        "marks": 4,
        "options": [],
        "is_active": true,
        "created_by": 1,
        "answer_text": "Essential",
        "explanation": "Essential"
    },
    {
        "id": 47,
        "question_type": "SUBJECTIVE",
        "subject_type": "WRITTEN",
        "exam_level": "FRESHER",
        "question_text": "Milestone",
        "image_url": null,
        "passage": null,
        "marks": 4,
        "options": [],
        "is_active": true,
        "created_by": 1,
        "answer_text": "Milestone",
        "explanation": "Milestone"
    },
    {
        "id": 48,
        "question_type": "SUBJECTIVE",
        "subject_type": "WRITTEN",
        "exam_level": "FRESHER",
        "question_text": "Preferred",
        "image_url": null,
        "passage": null,
        "marks": 4,
        "options": [],
        "is_active": true,
        "created_by": 1,
        "answer_text": "Preferred",
        "explanation": "Preferred"
    },
    {
        "id": 49,
        "question_type": "SUBJECTIVE",
        "subject_type": "WRITTEN",
        "exam_level": "FRESHER",
        "question_text": "Empower",
        "image_url": null,
        "passage": null,
        "marks": 4,
        "options": [],
        "is_active": true,
        "created_by": 1,
        "answer_text": "Empower",
        "explanation": "Empower"
    },
    {
        "id": 50,
        "question_type": "SUBJECTIVE",
        "subject_type": "WRITTEN",
        "exam_level": "FRESHER",
        "question_text": "Optimistic",
        "image_url": null,
        "passage": null,
        "marks": 4,
        "options": [],
        "is_active": true,
        "created_by": 1,
        "answer_text": "Optimistic",
        "explanation": "Optimistic"
    },
    {
        "id": 51,
        "question_type": "SUBJECTIVE",
        "subject_type": "WRITTEN",
        "exam_level": "FRESHER",
        "question_text": "Compute",
        "image_url": null,
        "passage": null,
        "marks": 4,
        "options": [],
        "is_active": true,
        "created_by": 1,
        "answer_text": "Compute",
        "explanation": "Compute"
    },
    {
        "id": 52,
        "question_type": "SUBJECTIVE",
        "subject_type": "WRITTEN",
        "exam_level": "FRESHER",
        "question_text": "Reliable",
        "image_url": null,
        "passage": null,
        "marks": 4,
        "options": [],
        "is_active": true,
        "created_by": 1,
        "answer_text": "Reliable",
        "explanation": "Reliable"
    },
    {
        "id": 53,
        "question_type": "SUBJECTIVE",
        "subject_type": "WRITTEN",
        "exam_level": "FRESHER",
        "question_text": "Ahead",
        "image_url": null,
        "passage": null,
        "marks": 4,
        "options": [],
        "is_active": true,
        "created_by": 1,
        "answer_text": "Ahead",
        "explanation": "Ahead"
    },
    {
        "id": 54,
        "question_type": "SUBJECTIVE",
        "subject_type": "WRITTEN",
        "exam_level": "FRESHER",
        "question_text": "Benchmark",
        "image_url": null,
        "passage": null,
        "marks": 4,
        "options": [],
        "is_active": true,
        "created_by": 1,
        "answer_text": "Benchmark",
        "explanation": "Benchmark"
    },
    {
        "id": 55,
        "question_type": "SUBJECTIVE",
        "subject_type": "ENGLISH_GRAMMAR",
        "exam_level": "FRESHER",
        "question_text": "finish? / you / when / will / project / the",
        "image_url": null,
        "passage": null,
        "marks": 4,
        "options": [],
        "is_active": true,
        "created_by": 1,
        "answer_text": "When will you finish the project?",
        "explanation": "When will you finish the project?"
    },
    {
        "id": 56,
        "question_type": "SUBJECTIVE",
        "subject_type": "ENGLISH_GRAMMAR",
        "exam_level": "FRESHER",
        "question_text": "doing / what / are / you / here?",
        "image_url": null,
        "passage": null,
        "marks": 4,
        "options": [],
        "is_active": true,
        "created_by": 1,
        "answer_text": "What are you doing here?",
        "explanation": "What are you doing here?"
    },
    {
        "id": 57,
        "question_type": "SUBJECTIVE",
        "subject_type": "ENGLISH_GRAMMAR",
        "exam_level": "FRESHER",
        "question_text": "essential / is / health / for / exercise / good",
        "image_url": null,
        "passage": null,
        "marks": 4,
        "options": [],
        "is_active": true,
        "created_by": 1,
        "answer_text": "Exercise is essential for good health.",
        "explanation": "Exercise is essential for good health."
    },
    {
        "id": 58,
        "question_type": "SUBJECTIVE",
        "subject_type": "ENGLISH_GRAMMAR",
        "exam_level": "FRESHER",
        "question_text": "delayed / why / been / the flight / has?",
        "image_url": null,
        "passage": null,
        "marks": 4,
        "options": [],
        "is_active": true,
        "created_by": 1,
        "answer_text": "Why has the flight been delayed?",
        "explanation": "Why has the flight been delayed?"
    },
    {
        "id": 59,
        "question_type": "SUBJECTIVE",
        "subject_type": "ENGLISH_GRAMMAR",
        "exam_level": "FRESHER",
        "question_text": "team? / who / the / led / winning",
        "image_url": null,
        "passage": null,
        "marks": 4,
        "options": [],
        "is_active": true,
        "created_by": 1,
        "answer_text": "Who led the winning team?",
        "explanation": "Who led the winning team?"
    },
    {
        "id": 60,
        "question_type": "SUBJECTIVE",
        "subject_type": "ENGLISH_GRAMMAR",
        "exam_level": "FRESHER",
        "question_text": "to / need / do / we / how / long / wait / here?",
        "image_url": null,
        "passage": null,
        "marks": 1,
        "options": [],
        "is_active": true,
        "created_by": 1,
        "answer_text": "How long do we need to wait here?",
        "explanation": "How long do we need to wait here?"
    },
    {
        "id": 61,
        "question_type": "SUBJECTIVE",
        "subject_type": "ENGLISH_GRAMMAR",
        "exam_level": "FRESHER",
        "question_text": "week. / launch / was / to / next / set / The product",
        "image_url": null,
        "passage": null,
        "marks": 1,
        "options": [],
        "is_active": true,
        "created_by": 1,
        "answer_text": "The product was set to launch next week.",
        "explanation": "The product was set to launch next week."
    },
    {
        "id": 62,
        "question_type": "SUBJECTIVE",
        "subject_type": "ENGLISH_GRAMMAR",
        "exam_level": "FRESHER",
        "question_text": "success, / if / up / you / want to / give / don't / achieve",
        "image_url": null,
        "passage": null,
        "marks": 1,
        "options": [],
        "is_active": true,
        "created_by": 1,
        "answer_text": "If you want to achieve success, don't give up.",
        "explanation": "If you want to achieve success, don't give up."
    },
    {
        "id": 63,
        "question_type": "SUBJECTIVE",
        "subject_type": "ENGLISH_GRAMMAR",
        "exam_level": "FRESHER",
        "question_text": "blue sky / and admired / the stars / the boy / looked up at / the vast",
        "image_url": null,
        "passage": null,
        "marks": 1,
        "options": [],
        "is_active": true,
        "created_by": 1,
        "answer_text": "The boy looked up at the vast blue sky and admired the stars.",
        "explanation": "The boy looked up at the vast blue sky and admired the stars."
    },
    {
        "id": 64,
        "question_type": "SUBJECTIVE",
        "subject_type": "ENGLISH_GRAMMAR",
        "exam_level": "FRESHER",
        "question_text": "quickly. / So / he / treated / his / sprained / ankle",
        "image_url": null,
        "passage": null,
        "marks": 1,
        "options": [],
        "is_active": true,
        "created_by": 1,
        "answer_text": "So he treated his sprained ankle quickly.",
        "explanation": "So he treated his sprained ankle quickly."
    },
    {
        "id": 65,
        "question_type": "SUBJECTIVE",
        "subject_type": "ENGLISH_GRAMMAR",
        "exam_level": "FRESHER",
        "question_text": "on. / see / to / what / was / rushed / Everyone / going",
        "image_url": null,
        "passage": null,
        "marks": 1,
        "options": [],
        "is_active": true,
        "created_by": 1,
        "answer_text": "Everyone rushed to see what was going on.",
        "explanation": "Everyone rushed to see what was going on."
    },
    {
        "id": 66,
        "question_type": "PASSAGE_CONTENT",
        "subject_type": "COMPREHENSION",
        "exam_level": "FRESHER",
        "question_text": "According to the passage, what was the chief contribution of Edison's invention?",
        "image_url": null,
        "passage": "Darkness had ruled the night for centuries until a persistent inventor in Menlo Park decided otherwise. Thomas Alva Edison, born in Ohio in 1847, was a curious child who was often labelled as inattentive by his teachers. His mother, a former schoolteacher, took charge of his education at home, nurturing his love for experimentation. As a young man, Edison worked as a telegraph operator, but his real passion lay in tinkering with machines during his free hours. He believed that persistence, more than genius, was the key to invention. After thousands of failed attempts with different filament materials, Edison finally succeeded in 1879 in creating a carbon filament bulb that could glow for over thirteen hours. This breakthrough transformed daily life, allowing factories, homes and streets to be lit long after sunset. Edison was not only an inventor but also a shrewd businessman; he established the Edison Electric Light Company to bring his invention to ordinary households. He held over a thousand patents by the end of his life and remained devoted to experimentation until his final years. When he passed away in 1931, several cities across the United States dimmed their lights briefly in his honour, a quiet tribute to the man who had once lit up the world.",
        "marks": 2,
        "options": [{"image_url": null, "is_correct": false, "option_text": "It allowed telegraph operators to work at night", "option_label": "A"}, {"image_url": null, "is_correct": true, "option_text": "It enabled daily life to continue after sunset", "option_label": "B"}, {"image_url": null, "is_correct": false, "option_text": "It made Edison a wealthy businessman", "option_label": "C"}, {"image_url": null, "is_correct": false, "option_text": "It helped factories reduce production costs", "option_label": "D"}],
        "is_active": true,
        "created_by": 1,
        "answer_text": "B",
        "explanation": "nan"
    },
    {
        "id": 67,
        "question_type": "PASSAGE_CONTENT",
        "subject_type": "COMPREHENSION",
        "exam_level": "FRESHER",
        "question_text": "Which of the following helped Edison succeed in inventing the light bulb?",
        "image_url": null,
        "passage": "Darkness had ruled the night for centuries until a persistent inventor in Menlo Park decided otherwise. Thomas Alva Edison, born in Ohio in 1847, was a curious child who was often labelled as inattentive by his teachers. His mother, a former schoolteacher, took charge of his education at home, nurturing his love for experimentation. As a young man, Edison worked as a telegraph operator, but his real passion lay in tinkering with machines during his free hours. He believed that persistence, more than genius, was the key to invention. After thousands of failed attempts with different filament materials, Edison finally succeeded in 1879 in creating a carbon filament bulb that could glow for over thirteen hours. This breakthrough transformed daily life, allowing factories, homes and streets to be lit long after sunset. Edison was not only an inventor but also a shrewd businessman; he established the Edison Electric Light Company to bring his invention to ordinary households. He held over a thousand patents by the end of his life and remained devoted to experimentation until his final years. When he passed away in 1931, several cities across the United States dimmed their lights briefly in his honour, a quiet tribute to the man who had once lit up the world.",
        "marks": 2,
        "options": [{"image_url": null, "is_correct": false, "option_text": "His formal schooling", "option_label": "A"}, {"image_url": null, "is_correct": false, "option_text": "His work as a telegraph operator", "option_label": "B"}, {"image_url": null, "is_correct": true, "option_text": "His persistence despite repeated failures", "option_label": "C"}, {"image_url": null, "is_correct": false, "option_text": "Support from the government", "option_label": "D"}],
        "is_active": true,
        "created_by": 1,
        "answer_text": "C",
        "explanation": "nan"
    },
    {
        "id": 68,
        "question_type": "PASSAGE_CONTENT",
        "subject_type": "COMPREHENSION",
        "exam_level": "FRESHER",
        "question_text": "Edison's approach to invention can be best described as one of ______.",
        "image_url": null,
        "passage": "Darkness had ruled the night for centuries until a persistent inventor in Menlo Park decided otherwise. Thomas Alva Edison, born in Ohio in 1847, was a curious child who was often labelled as inattentive by his teachers. His mother, a former schoolteacher, took charge of his education at home, nurturing his love for experimentation. As a young man, Edison worked as a telegraph operator, but his real passion lay in tinkering with machines during his free hours. He believed that persistence, more than genius, was the key to invention. After thousands of failed attempts with different filament materials, Edison finally succeeded in 1879 in creating a carbon filament bulb that could glow for over thirteen hours. This breakthrough transformed daily life, allowing factories, homes and streets to be lit long after sunset. Edison was not only an inventor but also a shrewd businessman; he established the Edison Electric Light Company to bring his invention to ordinary households. He held over a thousand patents by the end of his life and remained devoted to experimentation until his final years. When he passed away in 1931, several cities across the United States dimmed their lights briefly in his honour, a quiet tribute to the man who had once lit up the world.",
        "marks": 2,
        "options": [{"image_url": null, "is_correct": false, "option_text": "Relying purely on natural talent", "option_label": "A"}, {"image_url": null, "is_correct": false, "option_text": "Learning solely from his teachers", "option_label": "B"}, {"image_url": null, "is_correct": true, "option_text": "Persistent experimentation despite setbacks", "option_label": "C"}, {"image_url": null, "is_correct": false, "option_text": "Following instructions from mentors", "option_label": "D"}],
        "is_active": true,
        "created_by": 1,
        "answer_text": "C",
        "explanation": "nan"
    },
    {
        "id": 69,
        "question_type": "PASSAGE_CONTENT",
        "subject_type": "COMPREHENSION",
        "exam_level": "FRESHER",
        "question_text": "Choose the word which is NOT NEARLY THE SAME in meaning as the word printed in bold: 'Persistent'",
        "image_url": null,
        "passage": "Darkness had ruled the night for centuries until a persistent inventor in Menlo Park decided otherwise. Thomas Alva Edison, born in Ohio in 1847, was a curious child who was often labelled as inattentive by his teachers. His mother, a former schoolteacher, took charge of his education at home, nurturing his love for experimentation. As a young man, Edison worked as a telegraph operator, but his real passion lay in tinkering with machines during his free hours. He believed that persistence, more than genius, was the key to invention. After thousands of failed attempts with different filament materials, Edison finally succeeded in 1879 in creating a carbon filament bulb that could glow for over thirteen hours. This breakthrough transformed daily life, allowing factories, homes and streets to be lit long after sunset. Edison was not only an inventor but also a shrewd businessman; he established the Edison Electric Light Company to bring his invention to ordinary households. He held over a thousand patents by the end of his life and remained devoted to experimentation until his final years. When he passed away in 1931, several cities across the United States dimmed their lights briefly in his honour, a quiet tribute to the man who had once lit up the world.",
        "marks": 2,
        "options": [{"image_url": null, "is_correct": false, "option_text": "Determined", "option_label": "A"}, {"image_url": null, "is_correct": false, "option_text": "Tenacious", "option_label": "B"}, {"image_url": null, "is_correct": false, "option_text": "Unwavering", "option_label": "C"}, {"image_url": null, "is_correct": true, "option_text": "Fickle", "option_label": "D"}],
        "is_active": true,
        "created_by": 1,
        "answer_text": "D",
        "explanation": "nan"
    },
    {
        "id": 70,
        "question_type": "PASSAGE_CONTENT",
        "subject_type": "COMPREHENSION",
        "exam_level": "FRESHER",
        "question_text": "Choose the word which is MOST OPPOSITE in meaning of the word printed in bold: 'Curious'",
        "image_url": null,
        "passage": "Darkness had ruled the night for centuries until a persistent inventor in Menlo Park decided otherwise. Thomas Alva Edison, born in Ohio in 1847, was a curious child who was often labelled as inattentive by his teachers. His mother, a former schoolteacher, took charge of his education at home, nurturing his love for experimentation. As a young man, Edison worked as a telegraph operator, but his real passion lay in tinkering with machines during his free hours. He believed that persistence, more than genius, was the key to invention. After thousands of failed attempts with different filament materials, Edison finally succeeded in 1879 in creating a carbon filament bulb that could glow for over thirteen hours. This breakthrough transformed daily life, allowing factories, homes and streets to be lit long after sunset. Edison was not only an inventor but also a shrewd businessman; he established the Edison Electric Light Company to bring his invention to ordinary households. He held over a thousand patents by the end of his life and remained devoted to experimentation until his final years. When he passed away in 1931, several cities across the United States dimmed their lights briefly in his honour, a quiet tribute to the man who had once lit up the world.",
        "marks": 2,
        "options": [{"image_url": null, "is_correct": false, "option_text": "Inquisitive", "option_label": "A"}, {"image_url": null, "is_correct": true, "option_text": "Indifferent", "option_label": "B"}, {"image_url": null, "is_correct": false, "option_text": "Eager", "option_label": "C"}, {"image_url": null, "is_correct": false, "option_text": "Attentive", "option_label": "D"}],
        "is_active": true,
        "created_by": 1,
        "answer_text": "B",
        "explanation": "nan"
    },
    {
        "id": 71,
        "question_type": "PASSAGE_CONTENT",
        "subject_type": "COMPREHENSION",
        "exam_level": "FRESHER",
        "question_text": "Choose the word which is MOST OPPOSITE in meaning of the word printed in bold: 'Shrewd'",
        "image_url": null,
        "passage": "Darkness had ruled the night for centuries until a persistent inventor in Menlo Park decided otherwise. Thomas Alva Edison, born in Ohio in 1847, was a curious child who was often labelled as inattentive by his teachers. His mother, a former schoolteacher, took charge of his education at home, nurturing his love for experimentation. As a young man, Edison worked as a telegraph operator, but his real passion lay in tinkering with machines during his free hours. He believed that persistence, more than genius, was the key to invention. After thousands of failed attempts with different filament materials, Edison finally succeeded in 1879 in creating a carbon filament bulb that could glow for over thirteen hours. This breakthrough transformed daily life, allowing factories, homes and streets to be lit long after sunset. Edison was not only an inventor but also a shrewd businessman; he established the Edison Electric Light Company to bring his invention to ordinary households. He held over a thousand patents by the end of his life and remained devoted to experimentation until his final years. When he passed away in 1931, several cities across the United States dimmed their lights briefly in his honour, a quiet tribute to the man who had once lit up the world.",
        "marks": 2,
        "options": [{"image_url": null, "is_correct": false, "option_text": "Cunning", "option_label": "A"}, {"image_url": null, "is_correct": true, "option_text": "Naive", "option_label": "B"}, {"image_url": null, "is_correct": false, "option_text": "Sharp", "option_label": "C"}, {"image_url": null, "is_correct": false, "option_text": "Clever", "option_label": "D"}],
        "is_active": true,
        "created_by": 1,
        "answer_text": "B",
        "explanation": "nan"
    },
    {
        "id": 72,
        "question_type": "PASSAGE_CONTENT",
        "subject_type": "COMPREHENSION",
        "exam_level": "FRESHER",
        "question_text": "Choose the word which is MOST NEARLY THE SAME in meaning as the word printed in bold: 'Transform'",
        "image_url": null,
        "passage": "Darkness had ruled the night for centuries until a persistent inventor in Menlo Park decided otherwise. Thomas Alva Edison, born in Ohio in 1847, was a curious child who was often labelled as inattentive by his teachers. His mother, a former schoolteacher, took charge of his education at home, nurturing his love for experimentation. As a young man, Edison worked as a telegraph operator, but his real passion lay in tinkering with machines during his free hours. He believed that persistence, more than genius, was the key to invention. After thousands of failed attempts with different filament materials, Edison finally succeeded in 1879 in creating a carbon filament bulb that could glow for over thirteen hours. This breakthrough transformed daily life, allowing factories, homes and streets to be lit long after sunset. Edison was not only an inventor but also a shrewd businessman; he established the Edison Electric Light Company to bring his invention to ordinary households. He held over a thousand patents by the end of his life and remained devoted to experimentation until his final years. When he passed away in 1931, several cities across the United States dimmed their lights briefly in his honour, a quiet tribute to the man who had once lit up the world.",
        "marks": 2,
        "options": [{"image_url": null, "is_correct": false, "option_text": "Damage severely", "option_label": "A"}, {"image_url": null, "is_correct": true, "option_text": "Change completely", "option_label": "B"}, {"image_url": null, "is_correct": false, "option_text": "Remain constant", "option_label": "C"}, {"image_url": null, "is_correct": false, "option_text": "Slow down", "option_label": "D"}],
        "is_active": true,
        "created_by": 1,
        "answer_text": "B",
        "explanation": "nan"
    },
    {
        "id": 73,
        "question_type": "PASSAGE_CONTENT",
        "subject_type": "COMPREHENSION",
        "exam_level": "FRESHER",
        "question_text": "The tribute paid by American cities upon Edison's death suggests that he was held in:",
        "image_url": null,
        "passage": "Darkness had ruled the night for centuries until a persistent inventor in Menlo Park decided otherwise. Thomas Alva Edison, born in Ohio in 1847, was a curious child who was often labelled as inattentive by his teachers. His mother, a former schoolteacher, took charge of his education at home, nurturing his love for experimentation. As a young man, Edison worked as a telegraph operator, but his real passion lay in tinkering with machines during his free hours. He believed that persistence, more than genius, was the key to invention. After thousands of failed attempts with different filament materials, Edison finally succeeded in 1879 in creating a carbon filament bulb that could glow for over thirteen hours. This breakthrough transformed daily life, allowing factories, homes and streets to be lit long after sunset. Edison was not only an inventor but also a shrewd businessman; he established the Edison Electric Light Company to bring his invention to ordinary households. He held over a thousand patents by the end of his life and remained devoted to experimentation until his final years. When he passed away in 1931, several cities across the United States dimmed their lights briefly in his honour, a quiet tribute to the man who had once lit up the world.",
        "marks": 2,
        "options": [{"image_url": null, "is_correct": false, "option_text": "Contempt", "option_label": "A"}, {"image_url": null, "is_correct": false, "option_text": "Suspicion", "option_label": "B"}, {"image_url": null, "is_correct": true, "option_text": "High regard", "option_label": "C"}, {"image_url": null, "is_correct": false, "option_text": "Fear", "option_label": "D"}],
        "is_active": true,
        "created_by": 1,
        "answer_text": "C",
        "explanation": "nan"
    },
]


def seed_questions():
    db = SessionLocal()
    total_seeded = 0
    total_updated = 0
    try:
        for item in QUESTIONS_DATA:
            existing = db.query(Question).filter(Question.id == item["id"]).first()
            if existing:
                existing.question_type = item.get("question_type")
                existing.subject_type = item.get("subject_type")
                existing.exam_level = item.get("exam_level")
                existing.question_text = item.get("question_text")
                existing.image_url = item.get("image_url")
                existing.passage = item.get("passage")
                existing.marks = item.get("marks")
                existing.options = item.get("options")
                flag_modified(existing, "options")
                existing.is_active = item.get("is_active", True)

                ans = db.query(QuestionAnswer).filter(QuestionAnswer.question_id == existing.id).first()
                if ans:
                    ans.answer_text = item.get("answer_text", "")
                    ans.explanation = item.get("explanation", "")
                else:
                    new_ans = QuestionAnswer(
                        question_id=existing.id,
                        answer_text=item.get("answer_text", ""),
                        explanation=item.get("explanation", ""),
                        created_by=item.get("created_by", 1),
                    )
                    db.add(new_ans)
                total_updated += 1
            else:
                q_obj = Question(
                    id=item["id"],
                    question_type=item["question_type"],
                    subject_type=item["subject_type"],
                    exam_level=item["exam_level"],
                    question_text=item["question_text"],
                    image_url=item.get("image_url"),
                    passage=item.get("passage"),
                    marks=item.get("marks", 5),
                    options=item.get("options"),
                    is_active=item.get("is_active", True),
                    created_by=item.get("created_by", 1),
                )
                db.add(q_obj)
                db.flush()

                new_ans = QuestionAnswer(
                    question_id=q_obj.id,
                    answer_text=item.get("answer_text", ""),
                    explanation=item.get("explanation", ""),
                    created_by=item.get("created_by", 1),
                )
                db.add(new_ans)
                total_seeded += 1

        db.commit()
        print(f"✨ Questions seeding complete! Added: {total_seeded}, Updated: {total_updated}")
    except Exception as e:
        db.rollback()
        print(f"❌ Error seeding questions: {str(e)}")
    finally:
        db.close()

if __name__ == "__main__":
    seed_questions()
